{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "utils",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.11.0.jar",
          "url": "utils-0.11.0.jar",
          "size": 45173,
          "sha512": "cb4327bc8dadfac4ce175c46b0360ef521638b0781f755e330f6220258ff60fdd6563df420e7766b7a296900e368a0d0113a8750e94b622f8b0c4058e42ce236",
          "sha256": "399b61bfa3a01adaafa2931958388b35121c7b55ff43290958fa0922ce7dfb60",
          "sha1": "5894444ab4f60b9b072c3609608434f62d45c55f",
          "md5": "5b0c965cb8313d554a3afe0806c3bd19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.openjson",
          "module": "openjson",
          "version": {
            "requires": "1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.11.0.jar",
          "url": "utils-0.11.0.jar",
          "size": 45173,
          "sha512": "cb4327bc8dadfac4ce175c46b0360ef521638b0781f755e330f6220258ff60fdd6563df420e7766b7a296900e368a0d0113a8750e94b622f8b0c4058e42ce236",
          "sha256": "399b61bfa3a01adaafa2931958388b35121c7b55ff43290958fa0922ce7dfb60",
          "sha1": "5894444ab4f60b9b072c3609608434f62d45c55f",
          "md5": "5b0c965cb8313d554a3afe0806c3bd19"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.11.0-javadoc.jar",
          "url": "utils-0.11.0-javadoc.jar",
          "size": 180443,
          "sha512": "6045c9126ef25a54091f995071ac27fb2a43e0732881a9990628c320bf46756ab64b09c4a39dea8b7c19c23ed336f5b2e7d0a22189df6048d5d17bbabc0e03e4",
          "sha256": "810175208f06c61436fc7ccd6b4aeeca9c82f699abafe65ed26b65cb6be9118c",
          "sha1": "135e1c7526d306d91d430c8a214bb62454f512c8",
          "md5": "1fd73dca4e5778ded344b79ca4273c33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.11.0-sources.jar",
          "url": "utils-0.11.0-sources.jar",
          "size": 45960,
          "sha512": "80e6dc62330f263de2f1e8423edae4ec735854d9491a47d5c3b5d2810eab7c1e31ea4d05ebafbd01c886bcd148342b42150832d555a6112059b0c0595be6efc5",
          "sha256": "f2aa644d9a50a2bececd2c08410b2b72f0ffcfe215f5141a70ed709ce91707fd",
          "sha1": "942705f5359b7e879c59eb354dacf27d0513395e",
          "md5": "4ea2aef39e1650a8c17e6297f5b7f4f2"
        }
      ]
    }
  ]
}
