{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-arrow/2.0.0/kotest-assertions-arrow-2.0.0.module",
    "group": "io.kotest.extensions",
    "module": "kotest-assertions-arrow",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-jvm-2.0.0.jar",
          "url": "kotest-assertions-arrow-jvm-2.0.0.jar",
          "size": 28197,
          "sha512": "11055ef0d9879f72295b53cfbf3226e99837f0fd7e4d962a197447f52b0834928c1b860c9a3d8d41c4be2b3149859ed3f8d891fdb5a26a884b197ae14e092f2d",
          "sha256": "8695ea72a0b5d05e7acb717549600b3f7b097d131d5fc435a9d2cfce714265dd",
          "sha1": "4bc76d0d0c1d82ed7765d4355a4b4fd652c1d9d3",
          "md5": "e8794c906aac399bdd2e68b9e03c36c3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-jvm-2.0.0.jar",
          "url": "kotest-assertions-arrow-jvm-2.0.0.jar",
          "size": 28197,
          "sha512": "11055ef0d9879f72295b53cfbf3226e99837f0fd7e4d962a197447f52b0834928c1b860c9a3d8d41c4be2b3149859ed3f8d891fdb5a26a884b197ae14e092f2d",
          "sha256": "8695ea72a0b5d05e7acb717549600b3f7b097d131d5fc435a9d2cfce714265dd",
          "sha1": "4bc76d0d0c1d82ed7765d4355a4b4fd652c1d9d3",
          "md5": "e8794c906aac399bdd2e68b9e03c36c3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-jvm-2.0.0-sources.jar",
          "url": "kotest-assertions-arrow-jvm-2.0.0-sources.jar",
          "size": 5894,
          "sha512": "edb8c394e460e774481455161e5c61e9d13a494fecacbbe97074d98447b0a3544ef84c6c135134d5b6ecbcbab97f1c927d9f720dcdb885361da3aabea2d4e464",
          "sha256": "fab8024b4734a14401c6a662dbb78e5084ebd00507a1af7a9d04c2d3c7286cfc",
          "sha1": "5d406b55f191ccf62a8cb1c909a0ee1dc9ce0499",
          "md5": "472957b7a484184aec27ff805ac89af3"
        }
      ]
    }
  ]
}
