{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-strict/2.1.0/stately-strict-2.1.0.module",
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-jvm-2.1.0.jar",
          "url": "stately-strict-jvm-2.1.0.jar",
          "size": 1607,
          "sha512": "5fb52f5592470cd7aa2fa39ff9a391f63cf61ec7e7415121db0800501827f8e8398d54f4cd1daf05da970f61cf20afa20d02720e3858b75fc3fe1c6598f331f3",
          "sha256": "581070db2802cbad81f6e6e2d9d2494835443153b314458d53aa43c68260c9fa",
          "sha1": "3ae8369209065455f4630793bf6aca0fb88c8b6b",
          "md5": "4aa938e33acc448c4ebd7f0768480d22"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-jvm-2.1.0.jar",
          "url": "stately-strict-jvm-2.1.0.jar",
          "size": 1607,
          "sha512": "5fb52f5592470cd7aa2fa39ff9a391f63cf61ec7e7415121db0800501827f8e8398d54f4cd1daf05da970f61cf20afa20d02720e3858b75fc3fe1c6598f331f3",
          "sha256": "581070db2802cbad81f6e6e2d9d2494835443153b314458d53aa43c68260c9fa",
          "sha1": "3ae8369209065455f4630793bf6aca0fb88c8b6b",
          "md5": "4aa938e33acc448c4ebd7f0768480d22"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stately-strict-jvm-2.1.0-sources.jar",
          "url": "stately-strict-jvm-2.1.0-sources.jar",
          "size": 2718,
          "sha512": "690e395175abec803c3582066b6ad52692847b2838ff26a8dd1aa6bbb100999a6b8c85c752606d74d03c1a4fb3f593eb241db91862c7ebc5d63879820df111af",
          "sha256": "19cfdf3e5662c563c602f26e9a09abb39cb4186474143a4fa64d9b5eb30d9187",
          "sha1": "0c8f5004cbd0cec05789a5893eddcc78826c8030",
          "md5": "d55ef4ae8ad4d1a3dc6f41095f4700a3"
        }
      ]
    }
  ]
}
