{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrency/2.1.0/stately-concurrency-2.1.0.module",
    "group": "co.touchlab",
    "module": "stately-concurrency",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-jvm-2.1.0.jar",
          "url": "stately-concurrency-jvm-2.1.0.jar",
          "size": 11382,
          "sha512": "b6a98f9ea6d6ac5b1fedd170e621c7e8e07e9d8d894708e72db80766b2000378942ee41ff1eea1801bbf85bdc122301c664ba35d0243af02b3003030f3604b29",
          "sha256": "86739675892fb1c17d6bd36d05347e89ff313957421bb01a45a743ce774e8e29",
          "sha1": "6285428408c4d7e4a6d9a09511de877103effd81",
          "md5": "caa3a637b3459827e138cf78b9f31c55"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-jvm-2.1.0.jar",
          "url": "stately-concurrency-jvm-2.1.0.jar",
          "size": 11382,
          "sha512": "b6a98f9ea6d6ac5b1fedd170e621c7e8e07e9d8d894708e72db80766b2000378942ee41ff1eea1801bbf85bdc122301c664ba35d0243af02b3003030f3604b29",
          "sha256": "86739675892fb1c17d6bd36d05347e89ff313957421bb01a45a743ce774e8e29",
          "sha1": "6285428408c4d7e4a6d9a09511de877103effd81",
          "md5": "caa3a637b3459827e138cf78b9f31c55"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stately-concurrency-jvm-2.1.0-sources.jar",
          "url": "stately-concurrency-jvm-2.1.0-sources.jar",
          "size": 10485,
          "sha512": "39ee9e7393c3b10e69746785f61c2b8b9a8dc9cb154bf38bb870ead3d26fdde544d9015608d0e184d300f04c1f36afacbf1076d0667dee6f693cdf1456089e5c",
          "sha256": "1981bcea839e608ecce520237561ba640948be7e46316098d4fcfb7d9d19ca99",
          "sha1": "82b34a58a9de0828950f8923595e09fa7eb43c2b",
          "md5": "0f6077441ca30a0ec00ff2b398e25f47"
        }
      ]
    }
  ]
}
