{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sql-psi",
    "module": "core",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-0.5.2.jar",
          "url": "core-0.5.2.jar",
          "size": 507349,
          "sha512": "1727e0e4cc290b1f1c034f778357b9b0c7c0b1ef06f52a4b12b768b0fa9664b079743b872fef153e282d956d9615bbce8e9333149a4bc5aa443c4da88507d6ad",
          "sha256": "4afbae66631dde7134066d3d910ff23270c0e85c70e1b7f0e289752b6ac79e2c",
          "sha1": "e4dd730fc82982ce5a53872475d635dda525d64a",
          "md5": "fd2a342b09dfd7f6e8cda5ad4dd59604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-0.5.2.jar",
          "url": "core-0.5.2.jar",
          "size": 507349,
          "sha512": "1727e0e4cc290b1f1c034f778357b9b0c7c0b1ef06f52a4b12b768b0fa9664b079743b872fef153e282d956d9615bbce8e9333149a4bc5aa443c4da88507d6ad",
          "sha256": "4afbae66631dde7134066d3d910ff23270c0e85c70e1b7f0e289752b6ac79e2c",
          "sha1": "e4dd730fc82982ce5a53872475d635dda525d64a",
          "md5": "fd2a342b09dfd7f6e8cda5ad4dd59604"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sql-psi",
          "module": "environment",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-0.5.2-test-fixtures.jar",
          "url": "core-0.5.2-test-fixtures.jar",
          "size": 93742,
          "sha512": "6ad84a0a210412754d15cdbd405e174c92fe3d67a0d4e138429ac5eef8264b4ec3a7cd1a6a7716aa068f45b706a693ad17ab3afea9a6b421406363188b730727",
          "sha256": "b5fe76dd4c77276956b5960c2b4c74657a4890e980ac3c077f89832fc62751f5",
          "sha1": "576b36be43eef4b84005e32db09001e262dbaedc",
          "md5": "5df50bd2903e16f02a7a2b13913d6114"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sql-psi",
          "name": "core-test-fixtures",
          "version": "0.5.2"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sql-psi",
          "module": "environment",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-0.5.2-test-fixtures.jar",
          "url": "core-0.5.2-test-fixtures.jar",
          "size": 93742,
          "sha512": "6ad84a0a210412754d15cdbd405e174c92fe3d67a0d4e138429ac5eef8264b4ec3a7cd1a6a7716aa068f45b706a693ad17ab3afea9a6b421406363188b730727",
          "sha256": "b5fe76dd4c77276956b5960c2b4c74657a4890e980ac3c077f89832fc62751f5",
          "sha1": "576b36be43eef4b84005e32db09001e262dbaedc",
          "md5": "5df50bd2903e16f02a7a2b13913d6114"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sql-psi",
          "name": "core-test-fixtures",
          "version": "0.5.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.5.2-sources.jar",
          "url": "core-0.5.2-sources.jar",
          "size": 243341,
          "sha512": "c1158e9e9df857f2c3c8250707c03f79bbeaee05fb523eba54c4a94cb08eb862dabf43e3a99a0dc3f252fcab572898e03d08f530a3173854cc664fd802dfb8aa",
          "sha256": "6438412992cc26ea57c06ba0c24ec30700579bdb7e97fca7ec4a74bd53c71be5",
          "sha1": "df6725820fc54002ba8b88bf0fe714d7e463ccda",
          "md5": "c4597e1d3554564987bbe939a06772d0"
        }
      ]
    },
    {
      "name": "testFixturesSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.5.2-test-fixtures-sources.jar",
          "url": "core-0.5.2-test-fixtures-sources.jar",
          "size": 68051,
          "sha512": "de914b8bf85251e6753a74af00bf65fed128b670725b78270a78b906bb5481617b8b74e49648561547abeccb190506d5f9db4c669cc42872eb4697533c188c86",
          "sha256": "3a289713d5ec195e2c300e5c9a166b21ad91fa2aa22add8137c1c4709d7c1d4b",
          "sha1": "c8c939bd039bd38926d663c641ab77e0f81ab0c0",
          "md5": "99f0830f2840b5a94e79229e2bf9c863"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sql-psi",
          "name": "core-test-fixtures",
          "version": "0.5.2"
        }
      ]
    }
  ]
}
