{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockk-dsl/1.14.5/mockk-dsl-1.14.5.module",
    "group": "io.mockk",
    "module": "mockk-dsl",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.14.5.jar",
          "url": "mockk-dsl-jvm-1.14.5.jar",
          "size": 460092,
          "sha512": "74153b13d745787a594f89be6c39f90cbc294b4fd297391599274d5767e26f55f9a64d182f705cf1337fef871e39104302c591258442e6107a07339e035fb9ff",
          "sha256": "d01d6ce85f9824d8ddb22ea7f1bccd581b831ffad504f48a4f18abf9bc6f2eac",
          "sha1": "f23a3fe360fe7f8afac1f4f91602355cfd0e2517",
          "md5": "44ff8e7e4854107ed2ad4813a84cdd2e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "io.mockk",
          "module": "mockk-core",
          "version": {
            "requires": "1.14.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-dsl-jvm-1.14.5.jar",
          "url": "mockk-dsl-jvm-1.14.5.jar",
          "size": 460092,
          "sha512": "74153b13d745787a594f89be6c39f90cbc294b4fd297391599274d5767e26f55f9a64d182f705cf1337fef871e39104302c591258442e6107a07339e035fb9ff",
          "sha256": "d01d6ce85f9824d8ddb22ea7f1bccd581b831ffad504f48a4f18abf9bc6f2eac",
          "sha1": "f23a3fe360fe7f8afac1f4f91602355cfd0e2517",
          "md5": "44ff8e7e4854107ed2ad4813a84cdd2e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-dsl-jvm-1.14.5-sources.jar",
          "url": "mockk-dsl-jvm-1.14.5-sources.jar",
          "size": 24755,
          "sha512": "ee5155e5958ac2eec73f67b637e39db05a0631945b56d9de547b0d48e2d5a653809a36afc1a15fef173d66d34b883689c76b6caf8fafce6afdd23cc70352b996",
          "sha256": "a1b332c0536906d631408f70e2b27a9e9b4d43227ecf0b9b73cee364544bd6ce",
          "sha1": "369858a6b68108b805234dc1ee606b41aa8250ef",
          "md5": "ecf1bfeae7e6773c914c5d0e1e8c2501"
        }
      ]
    }
  ]
}
