{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-metadata-6.0.3.jar",
          "url": "kotest-assertions-shared-6.0.3.jar",
          "size": 12088,
          "sha512": "36c0103ba18d57ec473cc79c268e8ff6ac40ac12e36d0ae10664900d282f6b88e4a3a421e93c08a594e9dee725736b5614f62ea511dd792a7cd0ff6e3327a580",
          "sha256": "44dda6b0db56f25ae04933a7f4d20fac0fb247c2efce66828ef71383632dad58",
          "sha1": "c60c2a79784aa11553d8b30ab3a6fd5c58bfa7ee",
          "md5": "54bff39b61914bd32f0e43e78ee0fdf5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-kotlin-6.0.3-sources.jar",
          "url": "kotest-assertions-shared-6.0.3-sources.jar",
          "size": 11096,
          "sha512": "b65b1b718b417a99f6ec0603bd8386388f764c5ecf237ec2af8ecc5ca06dd3d96b957332e1c14b10708738b4d781ac5fd177978c3c6f7758a32e99d1018b7db6",
          "sha256": "bc850a6cf0f8f06677cabb7d0580b85c925c9ab945677425334a54c6108f52c4",
          "sha1": "352c7cb6a4094e800d084bb94588260f167d3767",
          "md5": "51b18550034186261a8e46a3fdb6a2b7"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm32/6.0.3/kotest-assertions-shared-androidnativearm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm32/6.0.3/kotest-assertions-shared-androidnativearm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm64/6.0.3/kotest-assertions-shared-androidnativearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativearm64/6.0.3/kotest-assertions-shared-androidnativearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex64/6.0.3/kotest-assertions-shared-androidnativex64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex64/6.0.3/kotest-assertions-shared-androidnativex64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex86/6.0.3/kotest-assertions-shared-androidnativex86-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex86",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-androidnativex86/6.0.3/kotest-assertions-shared-androidnativex86-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-androidnativex86",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosarm64/6.0.3/kotest-assertions-shared-iosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosarm64/6.0.3/kotest-assertions-shared-iosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosarm64/6.0.3/kotest-assertions-shared-iosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iossimulatorarm64/6.0.3/kotest-assertions-shared-iossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iossimulatorarm64/6.0.3/kotest-assertions-shared-iossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iossimulatorarm64/6.0.3/kotest-assertions-shared-iossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosx64/6.0.3/kotest-assertions-shared-iosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosx64/6.0.3/kotest-assertions-shared-iosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-iosx64/6.0.3/kotest-assertions-shared-iosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-iosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-js/6.0.3/kotest-assertions-shared-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-js/6.0.3/kotest-assertions-shared-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-js/6.0.3/kotest-assertions-shared-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-jvm/6.0.3/kotest-assertions-shared-jvm-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-jvm",
        "version": "6.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-jvm/6.0.3/kotest-assertions-shared-jvm-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-jvm",
        "version": "6.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-jvm/6.0.3/kotest-assertions-shared-jvm-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-jvm",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxarm64/6.0.3/kotest-assertions-shared-linuxarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxarm64/6.0.3/kotest-assertions-shared-linuxarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxx64/6.0.3/kotest-assertions-shared-linuxx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-linuxx64/6.0.3/kotest-assertions-shared-linuxx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-linuxx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosarm64/6.0.3/kotest-assertions-shared-macosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosarm64/6.0.3/kotest-assertions-shared-macosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosarm64/6.0.3/kotest-assertions-shared-macosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosx64/6.0.3/kotest-assertions-shared-macosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosx64/6.0.3/kotest-assertions-shared-macosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-macosx64/6.0.3/kotest-assertions-shared-macosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-macosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-mingwx64/6.0.3/kotest-assertions-shared-mingwx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-mingwx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-mingwx64/6.0.3/kotest-assertions-shared-mingwx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-mingwx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosarm64/6.0.3/kotest-assertions-shared-tvosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosarm64/6.0.3/kotest-assertions-shared-tvosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosarm64/6.0.3/kotest-assertions-shared-tvosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvossimulatorarm64/6.0.3/kotest-assertions-shared-tvossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvossimulatorarm64/6.0.3/kotest-assertions-shared-tvossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvossimulatorarm64/6.0.3/kotest-assertions-shared-tvossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosx64/6.0.3/kotest-assertions-shared-tvosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosx64/6.0.3/kotest-assertions-shared-tvosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-tvosx64/6.0.3/kotest-assertions-shared-tvosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-tvosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-js/6.0.3/kotest-assertions-shared-wasm-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-js/6.0.3/kotest-assertions-shared-wasm-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-js/6.0.3/kotest-assertions-shared-wasm-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-wasi/6.0.3/kotest-assertions-shared-wasm-wasi-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-wasi",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-wasi/6.0.3/kotest-assertions-shared-wasm-wasi-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-wasi",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-wasm-wasi/6.0.3/kotest-assertions-shared-wasm-wasi-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-wasm-wasi",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm32/6.0.3/kotest-assertions-shared-watchosarm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm32/6.0.3/kotest-assertions-shared-watchosarm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm32/6.0.3/kotest-assertions-shared-watchosarm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm64/6.0.3/kotest-assertions-shared-watchosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm64/6.0.3/kotest-assertions-shared-watchosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosarm64/6.0.3/kotest-assertions-shared-watchosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosdevicearm64/6.0.3/kotest-assertions-shared-watchosdevicearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosdevicearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosdevicearm64/6.0.3/kotest-assertions-shared-watchosdevicearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosdevicearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosdevicearm64/6.0.3/kotest-assertions-shared-watchosdevicearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosdevicearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchossimulatorarm64/6.0.3/kotest-assertions-shared-watchossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchossimulatorarm64/6.0.3/kotest-assertions-shared-watchossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchossimulatorarm64/6.0.3/kotest-assertions-shared-watchossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosx64/6.0.3/kotest-assertions-shared-watchosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosx64/6.0.3/kotest-assertions-shared-watchosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-shared-watchosx64/6.0.3/kotest-assertions-shared-watchosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-shared-watchosx64",
        "version": "6.0.3"
      }
    }
  ]
}
