{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.pdvrieze.xmlutil",
    "module": "serialization",
    "version": "0.91.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "core",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "core",
          "version": {
            "requires": "0.91.1"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-metadata-0.91.1.jar",
          "url": "serialization-0.91.1.jar",
          "size": 66365,
          "sha512": "06c7787a0e25eb73e187e51e28151a0d1896f484d34d77c9c4934bd59bf9b556119450c371cfe1c1ed3a79a68e7c97e549c1fcaf01fbd2fa66452a6416ce0ef8",
          "sha256": "1dfa2b1ffe73e1c6bbebce6c1731bf373e1761d38f19be57257d1a0eb0f96e95",
          "sha1": "94cf730d9a8a019b69bededde51a27012fdf5d84",
          "md5": "9e74c8955c1fe7e423fe21107922d187"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "serialization-kotlin-0.91.1-sources.jar",
          "url": "serialization-0.91.1-sources.jar",
          "size": 127409,
          "sha512": "88cda2028e035a20a2e9a355c8a288a116a0ca930b3d0e14cde615543fb04c07b3e7b3c1b397bd34646fe0b9ae7c26d28956bd1965bdaf08607ecca59203332c",
          "sha256": "6b5cb0db588c41c06f901030b58ecb5bbb18ad82fb6615b07918a576decd8b96",
          "sha1": "317e12226365bf8ee60177f57ce0d5d792592f92",
          "md5": "b4213cd821f5dea550d32e19c13139b2"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativearm32/0.91.1/serialization-androidnativearm32-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativearm32",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativearm32/0.91.1/serialization-androidnativearm32-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativearm32",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativearm64/0.91.1/serialization-androidnativearm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativearm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativearm64/0.91.1/serialization-androidnativearm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativearm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativex64/0.91.1/serialization-androidnativex64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativex64",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativex64/0.91.1/serialization-androidnativex64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativex64",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativex86/0.91.1/serialization-androidnativex86-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativex86",
        "version": "0.91.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-androidnativex86/0.91.1/serialization-androidnativex86-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-androidnativex86",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iosarm64/0.91.1/serialization-iosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iosarm64/0.91.1/serialization-iosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iosarm64/0.91.1/serialization-iosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iossimulatorarm64/0.91.1/serialization-iossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iossimulatorarm64/0.91.1/serialization-iossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iossimulatorarm64/0.91.1/serialization-iossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iosx64/0.91.1/serialization-iosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iosx64/0.91.1/serialization-iosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-iosx64/0.91.1/serialization-iosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-iosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../serialization-js/0.91.1/serialization-js-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-js",
        "version": "0.91.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../serialization-js/0.91.1/serialization-js-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-js",
        "version": "0.91.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../serialization-js/0.91.1/serialization-js-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-js",
        "version": "0.91.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../serialization-jvm/0.91.1/serialization-jvm-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-jvm",
        "version": "0.91.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../serialization-jvm/0.91.1/serialization-jvm-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-jvm",
        "version": "0.91.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../serialization-jvm/0.91.1/serialization-jvm-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-jvm",
        "version": "0.91.1"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-linuxarm32hfp/0.91.1/serialization-linuxarm32hfp-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-linuxarm32hfp",
        "version": "0.91.1"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-linuxarm32hfp/0.91.1/serialization-linuxarm32hfp-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-linuxarm32hfp",
        "version": "0.91.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-linuxarm64/0.91.1/serialization-linuxarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-linuxarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-linuxarm64/0.91.1/serialization-linuxarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-linuxarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-linuxx64/0.91.1/serialization-linuxx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-linuxx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-linuxx64/0.91.1/serialization-linuxx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-linuxx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-macosarm64/0.91.1/serialization-macosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-macosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-macosarm64/0.91.1/serialization-macosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-macosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-macosarm64/0.91.1/serialization-macosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-macosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-macosx64/0.91.1/serialization-macosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-macosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-macosx64/0.91.1/serialization-macosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-macosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-macosx64/0.91.1/serialization-macosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-macosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-mingwx64/0.91.1/serialization-mingwx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-mingwx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-mingwx64/0.91.1/serialization-mingwx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-mingwx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvosarm64/0.91.1/serialization-tvosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvosarm64/0.91.1/serialization-tvosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvosarm64/0.91.1/serialization-tvosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvossimulatorarm64/0.91.1/serialization-tvossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvossimulatorarm64/0.91.1/serialization-tvossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvossimulatorarm64/0.91.1/serialization-tvossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvosx64/0.91.1/serialization-tvosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvosx64/0.91.1/serialization-tvosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-tvosx64/0.91.1/serialization-tvosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-tvosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../serialization-wasm-js/0.91.1/serialization-wasm-js-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-wasm-js",
        "version": "0.91.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../serialization-wasm-js/0.91.1/serialization-wasm-js-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-wasm-js",
        "version": "0.91.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../serialization-wasm-js/0.91.1/serialization-wasm-js-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-wasm-js",
        "version": "0.91.1"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../serialization-wasm-wasi/0.91.1/serialization-wasm-wasi-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-wasm-wasi",
        "version": "0.91.1"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../serialization-wasm-wasi/0.91.1/serialization-wasm-wasi-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-wasm-wasi",
        "version": "0.91.1"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../serialization-wasm-wasi/0.91.1/serialization-wasm-wasi-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-wasm-wasi",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosarm32/0.91.1/serialization-watchosarm32-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosarm32",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosarm32/0.91.1/serialization-watchosarm32-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosarm32",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosarm32/0.91.1/serialization-watchosarm32-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosarm32",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosarm64/0.91.1/serialization-watchosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosarm64/0.91.1/serialization-watchosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosarm64/0.91.1/serialization-watchosarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosdevicearm64/0.91.1/serialization-watchosdevicearm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosdevicearm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosdevicearm64/0.91.1/serialization-watchosdevicearm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosdevicearm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosdevicearm64/0.91.1/serialization-watchosdevicearm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosdevicearm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchossimulatorarm64/0.91.1/serialization-watchossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchossimulatorarm64/0.91.1/serialization-watchossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchossimulatorarm64/0.91.1/serialization-watchossimulatorarm64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchossimulatorarm64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosx64/0.91.1/serialization-watchosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosx64/0.91.1/serialization-watchosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosx64",
        "version": "0.91.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../serialization-watchosx64/0.91.1/serialization-watchosx64-0.91.1.module",
        "group": "io.github.pdvrieze.xmlutil",
        "module": "serialization-watchosx64",
        "version": "0.91.1"
      }
    }
  ]
}
