{
  "formatVersion": "1.1",
  "component": {
    "group": "org.cyclonedx",
    "module": "cyclonedx-gradle-plugin",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cyclonedx-gradle-plugin-2.3.1.jar",
          "url": "cyclonedx-gradle-plugin-2.3.1.jar",
          "size": 61107,
          "sha512": "4541d9ea2d8d4bd1f25b49351c4aeb775ea40aa4db0908cf3f61acb46527ee4637ac8bcf375b99fe3c9e9f432db00925b991567de29bee35c1d835451653940d",
          "sha256": "0c6758d3eade6567c2a176d3cc2509aebbb1708e13d5456ec12b5206f8294bc1",
          "sha1": "5917a9094662567362da3a549c6292f2e06ef848",
          "md5": "b84f6e63fecfca446d93079317c7ac4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.cyclonedx",
          "module": "cyclonedx-core-java",
          "version": {
            "requires": "10.2.1"
          },
          "excludes": [
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-slf4j-impl"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-core",
          "version": {
            "requires": "3.9.9"
          }
        }
      ],
      "files": [
        {
          "name": "cyclonedx-gradle-plugin-2.3.1.jar",
          "url": "cyclonedx-gradle-plugin-2.3.1.jar",
          "size": 61107,
          "sha512": "4541d9ea2d8d4bd1f25b49351c4aeb775ea40aa4db0908cf3f61acb46527ee4637ac8bcf375b99fe3c9e9f432db00925b991567de29bee35c1d835451653940d",
          "sha256": "0c6758d3eade6567c2a176d3cc2509aebbb1708e13d5456ec12b5206f8294bc1",
          "sha1": "5917a9094662567362da3a549c6292f2e06ef848",
          "md5": "b84f6e63fecfca446d93079317c7ac4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyclonedx-gradle-plugin-2.3.1-javadoc.jar",
          "url": "cyclonedx-gradle-plugin-2.3.1-javadoc.jar",
          "size": 74378,
          "sha512": "ca32f93ee86c9f9b58a698cd46fedad02c37326a05cee26bb82f1a39a351f10f8dfdf3bf9c49749d430ec526839e51c7be5697133696a0536758ff0470a3ddca",
          "sha256": "6eaf36f77f99a3129ea80dcdac58a81b64bfa6c64f9287e50531352a847d7419",
          "sha1": "bbe9c6399203782d5f67328f553835c545180900",
          "md5": "ef588201292329e54001967d961fcc9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cyclonedx-gradle-plugin-2.3.1-sources.jar",
          "url": "cyclonedx-gradle-plugin-2.3.1-sources.jar",
          "size": 38402,
          "sha512": "2990cfe6d893b7f902cdd0c9263bd9aded9b2cb6d653e5acf3cf58316a86db1aac9c1903efc810180d70b14e42b8b26ff2633e08c147552e41bfb448b392cedf",
          "sha256": "7efe69d7ae33ab334713101738a8e2ac8974d9744da46be5e927f199113068e0",
          "sha1": "a9199c016350861d75677a01cdce952df12143c6",
          "md5": "cde674cc52ade57db168337b89934f32"
        }
      ]
    }
  ]
}
