{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib-extra",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-3.3.1.jar",
          "url": "spotless-lib-extra-3.3.1.jar",
          "size": 101471,
          "sha512": "18691c68ddb91ed7a356ac6a66890a18532fe90a759a54fece48cee9add48badc3eb91d672a91fa02f3e73c41bd8ac42420d72245b13ae1c9d77a8ce3936acbd",
          "sha256": "64c1219236fe562bdaa9aa3ba89531c3fab81ea232a4fffd46444df6399bf95a",
          "sha1": "29b2725d65215e614c4feee1dcaa301e9318f850",
          "md5": "16e222ba66ad01b42d0020c3602e3ec4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.10.1.202505221210-r"
          }
        },
        {
          "group": "com.googlecode.concurrent-trees",
          "module": "concurrent-trees",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "dev.equo.ide",
          "module": "solstice",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.osgi",
          "version": {
            "requires": "3.23.100"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-3.3.1.jar",
          "url": "spotless-lib-extra-3.3.1.jar",
          "size": 101471,
          "sha512": "18691c68ddb91ed7a356ac6a66890a18532fe90a759a54fece48cee9add48badc3eb91d672a91fa02f3e73c41bd8ac42420d72245b13ae1c9d77a8ce3936acbd",
          "sha256": "64c1219236fe562bdaa9aa3ba89531c3fab81ea232a4fffd46444df6399bf95a",
          "sha1": "29b2725d65215e614c4feee1dcaa301e9318f850",
          "md5": "16e222ba66ad01b42d0020c3602e3ec4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-3.3.1-javadoc.jar",
          "url": "spotless-lib-extra-3.3.1-javadoc.jar",
          "size": 151687,
          "sha512": "c7d8edfe5b6875390bf98870a93d70de260a6263a2e7c55901000b65d971cfa3b7336c2294ffed5c159e8feb01f7510c45f30984f5ae3dadd9b2ea3ac6258d54",
          "sha256": "b5e2aa4bf090e98e4321c6d22ac1c66bd413ff79b8947e1effcd7080a74281ce",
          "sha1": "d3d8a1f35827b78904e50d0033ad444e6eb6e481",
          "md5": "f99ec70db0d83044c002f14452681bd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-3.3.1-sources.jar",
          "url": "spotless-lib-extra-3.3.1-sources.jar",
          "size": 40334,
          "sha512": "34cdbfd7d3a5cd52bb2f960f318c9429d756fc57f2fb4d4a42268b40e9b50eda76ea3fc8e642915e32b15850fb8690c5bc5a17de1d9424c647e9fb9445042024",
          "sha256": "256982cbd2ccf5cc9b9c28fbb09933963bede44063ed4113e5df0c87872455f0",
          "sha1": "33922097d56bc29dbdd655f6eec48fcfb6e2c92b",
          "md5": "b7338258e434062c933f28ebf9b62007"
        }
      ]
    }
  ]
}
