{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spotless-lib-3.3.1.jar",
          "url": "spotless-lib-3.3.1.jar",
          "size": 601832,
          "sha512": "ac259892fd606f7fd52073d4b40d35c7dc8b85e22012b1647454b3a00cd8a044e2471a99855e10ae571e208bab5dcca8ff599b59afe39b10fed41ecfa2ef7b6d",
          "sha256": "7c74aa3d85e5f0563f06af05808cef62af8e378786f27dca40cfe817f402267b",
          "sha1": "24b9527ef553fe9c9603743651d408a122a132ff",
          "md5": "7ab6aa7564af11a4f02b1889ad239769"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-3.3.1.jar",
          "url": "spotless-lib-3.3.1.jar",
          "size": 601832,
          "sha512": "ac259892fd606f7fd52073d4b40d35c7dc8b85e22012b1647454b3a00cd8a044e2471a99855e10ae571e208bab5dcca8ff599b59afe39b10fed41ecfa2ef7b6d",
          "sha256": "7c74aa3d85e5f0563f06af05808cef62af8e378786f27dca40cfe817f402267b",
          "sha1": "24b9527ef553fe9c9603743651d408a122a132ff",
          "md5": "7ab6aa7564af11a4f02b1889ad239769"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-3.3.1-javadoc.jar",
          "url": "spotless-lib-3.3.1-javadoc.jar",
          "size": 611660,
          "sha512": "373fd99e59aa155f9dcf8fb4df9d19d2864a0f567b3fa16b82970333b2c12d4d47be75a89e2a7743dfe6c3e6b0f9db081931e893db7f5eb28e2ec929e4aa6bd4",
          "sha256": "d97778f85d23805401f490c8570a81a87fa9ae49f7f08246d0568f9a9e7dce53",
          "sha1": "5ee9ac8983346fd784da3bc98175445da1843822",
          "md5": "2d8cd9cc3a3c5e5458c2cdccd0f1439a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-3.3.1-sources.jar",
          "url": "spotless-lib-3.3.1-sources.jar",
          "size": 268380,
          "sha512": "892ba7f5dacdf89eee316af342b205c3cda9da5aafa22989b1240e025d01b9e01f9c34f5510c9a3ec7ff64b6d509409018c7d7336ade2912c1cce8854c4fc9da",
          "sha256": "ca2af11e275960b3b27db5a9e6436249559b53c5c0357ad460c5d26107414b48",
          "sha1": "4b07f11b08ffa90c8cb13e384044d1e59a2bd376",
          "md5": "e2691103f57a28fbde2885b037f738d0"
        }
      ]
    }
  ]
}
