{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-test/4.1.1/koin-test-4.1.1.module",
    "group": "io.insert-koin",
    "module": "koin-test",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core-annotations",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koin-test-jvm-4.1.1.jar",
          "url": "koin-test-jvm-4.1.1.jar",
          "size": 73593,
          "sha512": "32ba9d61e8eeb8ac4fe0b8f388020c4ae6a242c326d3fd07e9ea1899214b47d93471666ce688bfafc939610f706f990a0ee8440af16892fbe01b63f40ab01ba7",
          "sha256": "02e1c9fc1cb7c07590dfb87c3ed4532573ad9ba3f00524250250fce38b199280",
          "sha1": "8e0e3426df4f26fe1c6fd599f47cec00e7b554d3",
          "md5": "f62bf1a89bd660ecf43526c9e0e89b84"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core-annotations",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koin-test-jvm-4.1.1.jar",
          "url": "koin-test-jvm-4.1.1.jar",
          "size": 73593,
          "sha512": "32ba9d61e8eeb8ac4fe0b8f388020c4ae6a242c326d3fd07e9ea1899214b47d93471666ce688bfafc939610f706f990a0ee8440af16892fbe01b63f40ab01ba7",
          "sha256": "02e1c9fc1cb7c07590dfb87c3ed4532573ad9ba3f00524250250fce38b199280",
          "sha1": "8e0e3426df4f26fe1c6fd599f47cec00e7b554d3",
          "md5": "f62bf1a89bd660ecf43526c9e0e89b84"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koin-test-jvm-4.1.1-sources.jar",
          "url": "koin-test-jvm-4.1.1-sources.jar",
          "size": 14993,
          "sha512": "b2b23cac80ae23ac370f74d8ff82b733ef6125227c8d7ea7cb89cf4e55c2c1885edc79c00d8e93886de4b89b211a24bd02b0a662977cf9f4ae1854696e138c72",
          "sha256": "76e7aff246bc6b3fba7259e47c0df4f50bc3e83b0d7d81d01c28fa2a989fb29d",
          "sha1": "71136d3a4ee9f8725dcf96d9d0d65560e232cd82",
          "md5": "3e7c3bacd8ece82f223f739427169885"
        }
      ]
    }
  ]
}
