{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-framework-engine/6.0.3/kotest-framework-engine-6.0.3.module",
    "group": "io.kotest",
    "module": "kotest-framework-engine",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-jvm-6.0.3.jar",
          "url": "kotest-framework-engine-jvm-6.0.3.jar",
          "size": 1776779,
          "sha512": "667d968132513fb00ab8946b66ffb95245252f22cfb03ff0983528ed44d8ff3f7e91fc510f888301b1c60654ed25d174c9592871bf78618c8dd9bf18f0529a4a",
          "sha256": "125ea2c189b13e802ba717b79d032f06787b2d3ba76061ab3b361f1cc691ab14",
          "sha1": "6e0eedca6d8f2fbde6a2636dc870d6f8cd84bbb6",
          "md5": "e916261d46706709944e70c24525aebe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-framework-engine-jvm-6.0.3.jar",
          "url": "kotest-framework-engine-jvm-6.0.3.jar",
          "size": 1776779,
          "sha512": "667d968132513fb00ab8946b66ffb95245252f22cfb03ff0983528ed44d8ff3f7e91fc510f888301b1c60654ed25d174c9592871bf78618c8dd9bf18f0529a4a",
          "sha256": "125ea2c189b13e802ba717b79d032f06787b2d3ba76061ab3b361f1cc691ab14",
          "sha1": "6e0eedca6d8f2fbde6a2636dc870d6f8cd84bbb6",
          "md5": "e916261d46706709944e70c24525aebe"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-framework-engine-jvm-6.0.3-sources.jar",
          "url": "kotest-framework-engine-jvm-6.0.3-sources.jar",
          "size": 288910,
          "sha512": "1eaaadccd0c00795cc59de7d80ebbc8b445394eef16fa17d37d1acad8887e2d4eaf11d70d7da95007b5ff3770c21842e93665978314b14d3c8d33dafb517d56f",
          "sha256": "0a9e6338f3690a4e98f2501ab58b395238ab1b6582ca3c585b47c42ede94853b",
          "sha1": "a77eff1e7415fcb3f12fb70718723dc1b48dd6ad",
          "md5": "13079b2e50da1ca2670eeed98d0add5b"
        }
      ]
    }
  ]
}
