{
  "formatVersion": "1.1",
  "component": {
    "group": "co.touchlab",
    "module": "stately-concurrent-collections",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-metadata-2.1.0.jar",
          "url": "stately-concurrent-collections-2.1.0.jar",
          "size": 5718,
          "sha512": "d28dcb62290b88be3cecd946dd628e43f483ed8f119f71666ed7058ee7d34cf8199df0fa1ade3738aa261d93db52f64f38103a4c7771be36e6a575ff7d842e04",
          "sha256": "501a024be7377c2a853a775a2054a347fb47e0f999d20f63c3e42e2dc10172fa",
          "sha1": "9e89a13585209105912dcfa06c6ff565f261d790",
          "md5": "530e3e35ec7c86f75718517c9b14838b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "stately-concurrent-collections-kotlin-2.1.0-sources.jar",
          "url": "stately-concurrent-collections-2.1.0-sources.jar",
          "size": 4342,
          "sha512": "f9136afdc34d9b90c8b0f811ae21c70a49a4f7464d1bb7587ea19cbbd149d9754574369865646a77b22fb4cbf12dc08f124838fca162beea5ac13e259d917479",
          "sha256": "1507f2df766f32c7a265197ed3ad4f568e773b3e2d1f06e65b54386781df6f1a",
          "sha1": "285133d1b75d377c82036f1c773a7a2a32da5118",
          "md5": "4023abc1fef3f0666c88c93396ca9033"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativearm32/2.1.0/stately-concurrent-collections-androidnativearm32-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativearm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativearm32/2.1.0/stately-concurrent-collections-androidnativearm32-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativearm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativearm64/2.1.0/stately-concurrent-collections-androidnativearm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativearm64/2.1.0/stately-concurrent-collections-androidnativearm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativex64/2.1.0/stately-concurrent-collections-androidnativex64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativex64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativex64/2.1.0/stately-concurrent-collections-androidnativex64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativex64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativex86/2.1.0/stately-concurrent-collections-androidnativex86-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativex86",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-androidnativex86/2.1.0/stately-concurrent-collections-androidnativex86-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-androidnativex86",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosarm64/2.1.0/stately-concurrent-collections-iosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosarm64/2.1.0/stately-concurrent-collections-iosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosarm64/2.1.0/stately-concurrent-collections-iosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iossimulatorarm64/2.1.0/stately-concurrent-collections-iossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iossimulatorarm64/2.1.0/stately-concurrent-collections-iossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iossimulatorarm64/2.1.0/stately-concurrent-collections-iossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosx64/2.1.0/stately-concurrent-collections-iosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosx64/2.1.0/stately-concurrent-collections-iosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosx64/2.1.0/stately-concurrent-collections-iosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-js/2.1.0/stately-concurrent-collections-js-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-js/2.1.0/stately-concurrent-collections-js-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-js/2.1.0/stately-concurrent-collections-js-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-jvm/2.1.0/stately-concurrent-collections-jvm-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-jvm/2.1.0/stately-concurrent-collections-jvm-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-jvm/2.1.0/stately-concurrent-collections-jvm-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-linuxarm64/2.1.0/stately-concurrent-collections-linuxarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-linuxarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-linuxarm64/2.1.0/stately-concurrent-collections-linuxarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-linuxarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-linuxx64/2.1.0/stately-concurrent-collections-linuxx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-linuxx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-linuxx64/2.1.0/stately-concurrent-collections-linuxx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-linuxx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-macosarm64/2.1.0/stately-concurrent-collections-macosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-macosarm64/2.1.0/stately-concurrent-collections-macosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-macosarm64/2.1.0/stately-concurrent-collections-macosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-macosx64/2.1.0/stately-concurrent-collections-macosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-macosx64/2.1.0/stately-concurrent-collections-macosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-macosx64/2.1.0/stately-concurrent-collections-macosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-mingwx64/2.1.0/stately-concurrent-collections-mingwx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-mingwx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-mingwx64/2.1.0/stately-concurrent-collections-mingwx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-mingwx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvosarm64/2.1.0/stately-concurrent-collections-tvosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvosarm64/2.1.0/stately-concurrent-collections-tvosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvosarm64/2.1.0/stately-concurrent-collections-tvosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvossimulatorarm64/2.1.0/stately-concurrent-collections-tvossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvossimulatorarm64/2.1.0/stately-concurrent-collections-tvossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvossimulatorarm64/2.1.0/stately-concurrent-collections-tvossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvosx64/2.1.0/stately-concurrent-collections-tvosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvosx64/2.1.0/stately-concurrent-collections-tvosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-tvosx64/2.1.0/stately-concurrent-collections-tvosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-tvosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-wasm-js/2.1.0/stately-concurrent-collections-wasm-js-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-wasm-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-wasm-js/2.1.0/stately-concurrent-collections-wasm-js-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-wasm-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-wasm-js/2.1.0/stately-concurrent-collections-wasm-js-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-wasm-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosarm32/2.1.0/stately-concurrent-collections-watchosarm32-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosarm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosarm32/2.1.0/stately-concurrent-collections-watchosarm32-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosarm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosarm32/2.1.0/stately-concurrent-collections-watchosarm32-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosarm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosarm64/2.1.0/stately-concurrent-collections-watchosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosarm64/2.1.0/stately-concurrent-collections-watchosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosarm64/2.1.0/stately-concurrent-collections-watchosarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosdevicearm64/2.1.0/stately-concurrent-collections-watchosdevicearm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosdevicearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosdevicearm64/2.1.0/stately-concurrent-collections-watchosdevicearm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosdevicearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosdevicearm64/2.1.0/stately-concurrent-collections-watchosdevicearm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosdevicearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchossimulatorarm64/2.1.0/stately-concurrent-collections-watchossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchossimulatorarm64/2.1.0/stately-concurrent-collections-watchossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchossimulatorarm64/2.1.0/stately-concurrent-collections-watchossimulatorarm64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosx64/2.1.0/stately-concurrent-collections-watchosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosx64/2.1.0/stately-concurrent-collections-watchosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-watchosx64/2.1.0/stately-concurrent-collections-watchosx64-2.1.0.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-watchosx64",
        "version": "2.1.0"
      }
    }
  ]
}
