{
  "formatVersion": "1.1",
  "component": {
    "url": "../../arrow-core/2.1.2/arrow-core-2.1.2.module",
    "group": "io.arrow-kt",
    "module": "arrow-core",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.arrow-kt",
          "module": "arrow-atomic",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-annotations",
          "version": {
            "requires": "2.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "arrow-core-jvm-2.1.2.jar",
          "url": "arrow-core-jvm-2.1.2.jar",
          "size": 494749,
          "sha512": "c0fcb53de0c099c5b13cfaf16ae61e147ea15b2b154aa6d9b23933f97abe00d2f2c3f30e31ccca4bae2c4c5234d029b3be7b073b7b87bc564d761818bbfb4a01",
          "sha256": "26c4f0a5bdc0353c866ed5039bce489d5595726a78433f03e0b219a4a2803da8",
          "sha1": "0da256042c34d0633a156e2a16dfe2ffccfb2be0",
          "md5": "a54a9df53c451017a890ce34d77b0bd3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.arrow-kt",
          "module": "arrow-atomic",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-annotations",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "arrow-core-jvm-2.1.2.jar",
          "url": "arrow-core-jvm-2.1.2.jar",
          "size": 494749,
          "sha512": "c0fcb53de0c099c5b13cfaf16ae61e147ea15b2b154aa6d9b23933f97abe00d2f2c3f30e31ccca4bae2c4c5234d029b3be7b073b7b87bc564d761818bbfb4a01",
          "sha256": "26c4f0a5bdc0353c866ed5039bce489d5595726a78433f03e0b219a4a2803da8",
          "sha1": "0da256042c34d0633a156e2a16dfe2ffccfb2be0",
          "md5": "a54a9df53c451017a890ce34d77b0bd3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "arrow-core-jvm-2.1.2-sources.jar",
          "url": "arrow-core-jvm-2.1.2-sources.jar",
          "size": 73295,
          "sha512": "5b7b20bc2ee05ccaccdfb00931852de05494cb7696c744d9e636b803a9f361cfe9ee86361ba92290692197597acef7239fab4cb9463b8335d6ec0d4e52120c0d",
          "sha256": "cab0f405e08cc364f5a80529d991fc11cf4f4fb6c06af2f32ea6a7991857d3df",
          "sha1": "a3415b2d0b67fd3e5ee15b08ffe84c5191cd63cb",
          "md5": "84e5653186f543b23b16995b714aac84"
        }
      ]
    }
  ]
}
