{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-metadata-6.0.3.jar",
          "url": "kotest-assertions-core-6.0.3.jar",
          "size": 117990,
          "sha512": "129f47089950a5179100c3567ca081b98b88be6cfdfe515a278b3edd4e353d25a6f726e609a26590d3df14c623933c60091e87780c6afb8d2dc7f492dbddac2c",
          "sha256": "c6136e249569d164961fb6d3080711ca61a1c83e228ac6b37208a0e4c11643b2",
          "sha1": "61c2c28164d7b6e86b0857b5118938dc2c8efe47",
          "md5": "6c3a173ead75306815d7b49131891606"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-core-kotlin-6.0.3-sources.jar",
          "url": "kotest-assertions-core-6.0.3-sources.jar",
          "size": 161442,
          "sha512": "097133398e4169949f91255cd6203f692c1536d072df8e43acc19035247fdd2fdc73df808debed03b4353768fc76bd300deefc75157f4f5efcc4f3f30b9d7f27",
          "sha256": "58d818ecede1512897cf9e5536be0413d5dc78e5d8155a17d9463e16e2aa45a1",
          "sha1": "e6d42a9344416a3fcd20fc0d6e26971117716f59",
          "md5": "6d4c75f774a4eb4caad5dca42a0c7b2f"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm32/6.0.3/kotest-assertions-core-androidnativearm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm32/6.0.3/kotest-assertions-core-androidnativearm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm64/6.0.3/kotest-assertions-core-androidnativearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativearm64/6.0.3/kotest-assertions-core-androidnativearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex64/6.0.3/kotest-assertions-core-androidnativex64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex64/6.0.3/kotest-assertions-core-androidnativex64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex64",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex86/6.0.3/kotest-assertions-core-androidnativex86-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex86",
        "version": "6.0.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-androidnativex86/6.0.3/kotest-assertions-core-androidnativex86-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-androidnativex86",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosarm64/6.0.3/kotest-assertions-core-iosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosarm64/6.0.3/kotest-assertions-core-iosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosarm64/6.0.3/kotest-assertions-core-iosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iossimulatorarm64/6.0.3/kotest-assertions-core-iossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iossimulatorarm64/6.0.3/kotest-assertions-core-iossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iossimulatorarm64/6.0.3/kotest-assertions-core-iossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosx64/6.0.3/kotest-assertions-core-iosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosx64/6.0.3/kotest-assertions-core-iosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-iosx64/6.0.3/kotest-assertions-core-iosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-iosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/6.0.3/kotest-assertions-core-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/6.0.3/kotest-assertions-core-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-js/6.0.3/kotest-assertions-core-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/6.0.3/kotest-assertions-core-jvm-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "6.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/6.0.3/kotest-assertions-core-jvm-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "6.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-jvm/6.0.3/kotest-assertions-core-jvm-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-jvm",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxarm64/6.0.3/kotest-assertions-core-linuxarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxarm64/6.0.3/kotest-assertions-core-linuxarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxx64/6.0.3/kotest-assertions-core-linuxx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-linuxx64/6.0.3/kotest-assertions-core-linuxx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-linuxx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosarm64/6.0.3/kotest-assertions-core-macosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosarm64/6.0.3/kotest-assertions-core-macosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosarm64/6.0.3/kotest-assertions-core-macosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosx64/6.0.3/kotest-assertions-core-macosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosx64/6.0.3/kotest-assertions-core-macosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-macosx64/6.0.3/kotest-assertions-core-macosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-macosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-mingwx64/6.0.3/kotest-assertions-core-mingwx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-mingwx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-mingwx64/6.0.3/kotest-assertions-core-mingwx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-mingwx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosarm64/6.0.3/kotest-assertions-core-tvosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosarm64/6.0.3/kotest-assertions-core-tvosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosarm64/6.0.3/kotest-assertions-core-tvosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvossimulatorarm64/6.0.3/kotest-assertions-core-tvossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvossimulatorarm64/6.0.3/kotest-assertions-core-tvossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvossimulatorarm64/6.0.3/kotest-assertions-core-tvossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosx64/6.0.3/kotest-assertions-core-tvosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosx64/6.0.3/kotest-assertions-core-tvosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-tvosx64/6.0.3/kotest-assertions-core-tvosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-tvosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/6.0.3/kotest-assertions-core-wasm-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/6.0.3/kotest-assertions-core-wasm-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-js/6.0.3/kotest-assertions-core-wasm-js-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-js",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-wasi/6.0.3/kotest-assertions-core-wasm-wasi-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-wasi",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-wasi/6.0.3/kotest-assertions-core-wasm-wasi-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-wasi",
        "version": "6.0.3"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-wasm-wasi/6.0.3/kotest-assertions-core-wasm-wasi-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-wasm-wasi",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm32/6.0.3/kotest-assertions-core-watchosarm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm32/6.0.3/kotest-assertions-core-watchosarm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm32/6.0.3/kotest-assertions-core-watchosarm32-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm32",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm64/6.0.3/kotest-assertions-core-watchosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm64/6.0.3/kotest-assertions-core-watchosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosarm64/6.0.3/kotest-assertions-core-watchosarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosdevicearm64/6.0.3/kotest-assertions-core-watchosdevicearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosdevicearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosdevicearm64/6.0.3/kotest-assertions-core-watchosdevicearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosdevicearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosdevicearm64/6.0.3/kotest-assertions-core-watchosdevicearm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosdevicearm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchossimulatorarm64/6.0.3/kotest-assertions-core-watchossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchossimulatorarm64/6.0.3/kotest-assertions-core-watchossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchossimulatorarm64/6.0.3/kotest-assertions-core-watchossimulatorarm64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchossimulatorarm64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosx64/6.0.3/kotest-assertions-core-watchosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosx64/6.0.3/kotest-assertions-core-watchosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosx64",
        "version": "6.0.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-core-watchosx64/6.0.3/kotest-assertions-core-watchosx64-6.0.3.module",
        "group": "io.kotest",
        "module": "kotest-assertions-core-watchosx64",
        "version": "6.0.3"
      }
    }
  ]
}
