{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-3-30-dialect",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-25-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.1.0.jar",
          "url": "sqlite-3-30-dialect-2.1.0.jar",
          "size": 12984,
          "sha512": "47fb16318fc32249eb51871dfacb24ca53f506d100eff45240267091553ddf641a3d6a985b8b9f9b51c1fb656d3e9be0863c89386a3794608db9aed1edb63ed5",
          "sha256": "57774018ec8e807d79a06c1ed615ca98b9384138ee3f67c3e8bebabaa10d94e8",
          "sha1": "29ab2dca18e4819c24acfed836aca46bebfce06d",
          "md5": "dd575bd27f5d61b3e58d5e71b7e78794"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-25-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.1.0.jar",
          "url": "sqlite-3-30-dialect-2.1.0.jar",
          "size": 12984,
          "sha512": "47fb16318fc32249eb51871dfacb24ca53f506d100eff45240267091553ddf641a3d6a985b8b9f9b51c1fb656d3e9be0863c89386a3794608db9aed1edb63ed5",
          "sha256": "57774018ec8e807d79a06c1ed615ca98b9384138ee3f67c3e8bebabaa10d94e8",
          "sha1": "29ab2dca18e4819c24acfed836aca46bebfce06d",
          "md5": "dd575bd27f5d61b3e58d5e71b7e78794"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-30-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "compiler-env",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-25-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sqldelight",
              "name": "sqlite-3-25-dialect-test-fixtures"
            }
          ]
        },
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sql-psi",
              "name": "core-test-fixtures"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.1.0-test-fixtures.jar",
          "url": "sqlite-3-30-dialect-2.1.0-test-fixtures.jar",
          "size": 2590,
          "sha512": "06fe2d2d86b7f191d58aa3fdf82d89ab5d6dbb807ec3f8f40f57320b0e47d42efb4e81445ef566b0d3646becea0746f8fe89e616ad6d38562528df3482dc0f6a",
          "sha256": "843b44b3f974b6f93a8afa0cf00271ed7bc56605b36e0d7f5b3e29486bb01b90",
          "sha1": "c2c916fe232c2f7c07a5a5e398071ced9476efc6",
          "md5": "d2e22b13df5cbf2ef9d60575c76dde08"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sqldelight",
          "name": "sqlite-3-30-test-fixtures",
          "version": "2.1.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-30-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "compiler-env",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-25-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sqldelight",
              "name": "sqlite-3-25-dialect-test-fixtures"
            }
          ]
        },
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sql-psi",
              "name": "core-test-fixtures"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.1.0-test-fixtures.jar",
          "url": "sqlite-3-30-dialect-2.1.0-test-fixtures.jar",
          "size": 2590,
          "sha512": "06fe2d2d86b7f191d58aa3fdf82d89ab5d6dbb807ec3f8f40f57320b0e47d42efb4e81445ef566b0d3646becea0746f8fe89e616ad6d38562528df3482dc0f6a",
          "sha256": "843b44b3f974b6f93a8afa0cf00271ed7bc56605b36e0d7f5b3e29486bb01b90",
          "sha1": "c2c916fe232c2f7c07a5a5e398071ced9476efc6",
          "md5": "d2e22b13df5cbf2ef9d60575c76dde08"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sqldelight",
          "name": "sqlite-3-30-test-fixtures",
          "version": "2.1.0"
        }
      ]
    }
  ]
}
