{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-metadata-4.1.1.jar",
          "url": "koin-core-4.1.1.jar",
          "size": 56151,
          "sha512": "fa2d0f061fccc346010f1ae899af827ce34060f7869f1b12690304bac36146aa0201a2ac9cc7f3cb2f0b3e930fbd6e4a2d7e65a7fea1be0b238729167b3f42cd",
          "sha256": "df195ed534729ef41a30e10321ebb777fb59dd71fb833b0a6269b7e60e7e5f75",
          "sha1": "72f45a5b42ee9577e07c794ead01d236f6838fdf",
          "md5": "05811b6daf78889b5cdaf9d80f9372cb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "koin-core-kotlin-4.1.1-sources.jar",
          "url": "koin-core-4.1.1-sources.jar",
          "size": 74790,
          "sha512": "f93e01fa9017a382b7f343fd17ab36f460075a2f0c5d0586cf639578314fa9342bae1264d3af943c32d1ce186d32e91a0a8bfd2f039e6dbabba07f818da87689",
          "sha256": "093560eb10a2f44545905b711fb6ce8b8fe086b9579ba89836d560c0a48c9e23",
          "sha1": "e5b33ccd1f885c94ac0a96ac3592eceabc39446c",
          "md5": "03060392f2ea48a9aa81537ca3e52faf"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/4.1.1/koin-core-iosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/4.1.1/koin-core-iosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/4.1.1/koin-core-iosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iossimulatorarm64/4.1.1/koin-core-iossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iossimulatorarm64/4.1.1/koin-core-iossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iossimulatorarm64/4.1.1/koin-core-iossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/4.1.1/koin-core-iosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/4.1.1/koin-core-iosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/4.1.1/koin-core-iosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/4.1.1/koin-core-js-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "4.1.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/4.1.1/koin-core-js-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "4.1.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/4.1.1/koin-core-js-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "4.1.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/4.1.1/koin-core-jvm-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "4.1.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/4.1.1/koin-core-jvm-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "4.1.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/4.1.1/koin-core-jvm-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "4.1.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxarm64/4.1.1/koin-core-linuxarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxarm64/4.1.1/koin-core-linuxarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxx64/4.1.1/koin-core-linuxx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxx64/4.1.1/koin-core-linuxx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosarm64/4.1.1/koin-core-macosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosarm64/4.1.1/koin-core-macosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosarm64/4.1.1/koin-core-macosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/4.1.1/koin-core-macosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/4.1.1/koin-core-macosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/4.1.1/koin-core-macosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-mingwx64/4.1.1/koin-core-mingwx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-mingwx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-mingwx64/4.1.1/koin-core-mingwx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-mingwx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/4.1.1/koin-core-tvosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/4.1.1/koin-core-tvosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/4.1.1/koin-core-tvosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvossimulatorarm64/4.1.1/koin-core-tvossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvossimulatorarm64/4.1.1/koin-core-tvossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvossimulatorarm64/4.1.1/koin-core-tvossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/4.1.1/koin-core-tvosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/4.1.1/koin-core-tvosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/4.1.1/koin-core-tvosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koin-core-wasm-js/4.1.1/koin-core-wasm-js-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-wasm-js",
        "version": "4.1.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koin-core-wasm-js/4.1.1/koin-core-wasm-js-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-wasm-js",
        "version": "4.1.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../koin-core-wasm-js/4.1.1/koin-core-wasm-js-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-wasm-js",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/4.1.1/koin-core-watchosarm32-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/4.1.1/koin-core-watchosarm32-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/4.1.1/koin-core-watchosarm32-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/4.1.1/koin-core-watchosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/4.1.1/koin-core-watchosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/4.1.1/koin-core-watchosarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosdevicearm64/4.1.1/koin-core-watchosdevicearm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosdevicearm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosdevicearm64/4.1.1/koin-core-watchosdevicearm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosdevicearm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosdevicearm64/4.1.1/koin-core-watchosdevicearm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosdevicearm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchossimulatorarm64/4.1.1/koin-core-watchossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchossimulatorarm64/4.1.1/koin-core-watchossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchossimulatorarm64/4.1.1/koin-core-watchossimulatorarm64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchossimulatorarm64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/4.1.1/koin-core-watchosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/4.1.1/koin-core-watchosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "4.1.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/4.1.1/koin-core-watchosx64-4.1.1.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "4.1.1"
      }
    }
  ]
}
