{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.1.0/runtime-2.1.0.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-jvm-2.1.0.jar",
          "url": "runtime-jvm-2.1.0.jar",
          "size": 58690,
          "sha512": "9b605db243cabbc366f83ccdeee3403777b8bf8f9da73e17303efab47b5f50316d8eb5177b4b2f87b908d68237578242b70744d08a2a625d90aefad9868ce055",
          "sha256": "948a99350cbad763577469dbc7bf53fc58d8a2576b75f480f2830da49b0098ae",
          "sha1": "c2041f176390624670c7a53b9b78034c4405d775",
          "md5": "5bac733b6b1e011f882d362f1f1a6948"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-jvm-2.1.0.jar",
          "url": "runtime-jvm-2.1.0.jar",
          "size": 58690,
          "sha512": "9b605db243cabbc366f83ccdeee3403777b8bf8f9da73e17303efab47b5f50316d8eb5177b4b2f87b908d68237578242b70744d08a2a625d90aefad9868ce055",
          "sha256": "948a99350cbad763577469dbc7bf53fc58d8a2576b75f480f2830da49b0098ae",
          "sha1": "c2041f176390624670c7a53b9b78034c4405d775",
          "md5": "5bac733b6b1e011f882d362f1f1a6948"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runtime-jvm-2.1.0-sources.jar",
          "url": "runtime-jvm-2.1.0-sources.jar",
          "size": 17350,
          "sha512": "f74df077157814717c31f620de351c0d7b8c1c1426397d5b5b43d755b93094bda209b0529333f3c3a3d570cc179613e6ca093f1ed67c7c2ab4629565e3994142",
          "sha256": "f9906c1331cb54b88b5fdafae7308a2695405439dc1b3e4716123d8eccfb69be",
          "sha1": "b6a733196f1f822ae5fd164e21926bf4c3722bf5",
          "md5": "b07f322fda41534a9c8d3c6e8c4557ff"
        }
      ]
    }
  ]
}
