{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-extensions/6.0.3/kotest-extensions-6.0.3.module",
    "group": "io.kotest",
    "module": "kotest-extensions",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-jvm-6.0.3.jar",
          "url": "kotest-extensions-jvm-6.0.3.jar",
          "size": 56323,
          "sha512": "ad3a3c9cf490133c2662294dbaccf7f48a821b9e93a3c6b8d43479aed32205f50bc3bc2ebb2941654aade2c55cded2d6fa3ee23a28968c043f746d12e662ff1f",
          "sha256": "ee316d49b6bc1f08f6610f838ea669ea0218d752e1e90c91e450d5c26c575061",
          "sha1": "e9c27c2d26f498f12968b68ced6170193a153860",
          "md5": "2b071604859ddb706de74c08d6c92b34"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-framework-engine",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-extensions-jvm-6.0.3.jar",
          "url": "kotest-extensions-jvm-6.0.3.jar",
          "size": 56323,
          "sha512": "ad3a3c9cf490133c2662294dbaccf7f48a821b9e93a3c6b8d43479aed32205f50bc3bc2ebb2941654aade2c55cded2d6fa3ee23a28968c043f746d12e662ff1f",
          "sha256": "ee316d49b6bc1f08f6610f838ea669ea0218d752e1e90c91e450d5c26c575061",
          "sha1": "e9c27c2d26f498f12968b68ced6170193a153860",
          "md5": "2b071604859ddb706de74c08d6c92b34"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-extensions-jvm-6.0.3-sources.jar",
          "url": "kotest-extensions-jvm-6.0.3-sources.jar",
          "size": 10087,
          "sha512": "f632b93532b06be7b6134309d6e8c5fb8767ec61c1086bf82d94d72f8c01a43a8f9cd62fa9bb57dc0384ec5d32a95606c74f5f61f15ad3a5696ad9797f6eff0f",
          "sha256": "f46123791ce348a9f95d67faac0182be46df9f6d9bbe1211fcca1e75c57c09c4",
          "sha1": "e184d28482ca29145d49eb07c6fae9642c65fe74",
          "md5": "bfecbd24395d2fed2a94d437ec58c186"
        }
      ]
    }
  ]
}
