{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-3-38-dialect",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-35-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.1.0.jar",
          "url": "sqlite-3-38-dialect-2.1.0.jar",
          "size": 18052,
          "sha512": "09f1349a1b5aa42efc628139c824457d0757256b7cfadd56c1d2794851b1cc9b729fc4a54a448433a38053739147ae8e552752ac6489150334e17812d0b71062",
          "sha256": "83a7c163aaf6f146aebb178f1c5911c5a042fa4f70e78a27c585cdd7db93b42e",
          "sha1": "d051e3b3bf8146207956a8ba54528115f5dccddc",
          "md5": "84e733f8d8a4a957e454e35b12b7502a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-35-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.1.0.jar",
          "url": "sqlite-3-38-dialect-2.1.0.jar",
          "size": 18052,
          "sha512": "09f1349a1b5aa42efc628139c824457d0757256b7cfadd56c1d2794851b1cc9b729fc4a54a448433a38053739147ae8e552752ac6489150334e17812d0b71062",
          "sha256": "83a7c163aaf6f146aebb178f1c5911c5a042fa4f70e78a27c585cdd7db93b42e",
          "sha1": "d051e3b3bf8146207956a8ba54528115f5dccddc",
          "md5": "84e733f8d8a4a957e454e35b12b7502a"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-38-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "compiler-env",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-35-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sqldelight",
              "name": "sqlite-3-35-dialect-test-fixtures"
            }
          ]
        },
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sql-psi",
              "name": "core-test-fixtures"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.1.0-test-fixtures.jar",
          "url": "sqlite-3-38-dialect-2.1.0-test-fixtures.jar",
          "size": 2772,
          "sha512": "700007d77188d6d8b95b9614927119a2fdbda0e2511403dec2ae3fd3811e22cd2043fcd319c15651345cf97e08fba39ec9dd127f928cf3d781003b474f45ee0a",
          "sha256": "752f3f9b8df423a7ebbe4fac1ad7f3a7a79c6844b5e4be6b5aef9e115387821b",
          "sha1": "d8a551e8ebfda73ec2308d75a0425d430b4fbbaa",
          "md5": "225ff1dabf33a76ab596a14ce34f52e8"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sqldelight",
          "name": "sqlite-3-38-test-fixtures",
          "version": "2.1.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-38-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "compiler-env",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-35-dialect",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sqldelight",
              "name": "sqlite-3-35-dialect-test-fixtures"
            }
          ]
        },
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "app.cash.sql-psi",
              "name": "core-test-fixtures"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.1.0-test-fixtures.jar",
          "url": "sqlite-3-38-dialect-2.1.0-test-fixtures.jar",
          "size": 2772,
          "sha512": "700007d77188d6d8b95b9614927119a2fdbda0e2511403dec2ae3fd3811e22cd2043fcd319c15651345cf97e08fba39ec9dd127f928cf3d781003b474f45ee0a",
          "sha256": "752f3f9b8df423a7ebbe4fac1ad7f3a7a79c6844b5e4be6b5aef9e115387821b",
          "sha1": "d8a551e8ebfda73ec2308d75a0425d430b4fbbaa",
          "md5": "225ff1dabf33a76ab596a14ce34f52e8"
        }
      ],
      "capabilities": [
        {
          "group": "app.cash.sqldelight",
          "name": "sqlite-3-38-test-fixtures",
          "version": "2.1.0"
        }
      ]
    }
  ]
}
