{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-xml",
    "version": "2.18.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.18.3.jar",
          "url": "jackson-dataformat-xml-2.18.3.jar",
          "size": 129991,
          "sha512": "b52755634c9ba4aab7f48e7a40ae7c96928da437acab58775fc0824a976f0d58bea6463c6eae19cd4e7fb68a1129686554dd5bcebd107c8e095ad4d189c1a26",
          "sha256": "181c2e9f3d3ce8e03fd1ce240d202d129b2e53a3fed1aed2b69be4f29b1fb51",
          "sha1": "665a683773f8a92ea270d87127e198531e39cafa",
          "md5": "a39654d54dcddbacef53772658ce2cc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.18.3.jar",
          "url": "jackson-dataformat-xml-2.18.3.jar",
          "size": 129991,
          "sha512": "b52755634c9ba4aab7f48e7a40ae7c96928da437acab58775fc0824a976f0d58bea6463c6eae19cd4e7fb68a1129686554dd5bcebd107c8e095ad4d189c1a26",
          "sha256": "181c2e9f3d3ce8e03fd1ce240d202d129b2e53a3fed1aed2b69be4f29b1fb51",
          "sha1": "665a683773f8a92ea270d87127e198531e39cafa",
          "md5": "a39654d54dcddbacef53772658ce2cc5"
        }
      ]
    }
  ]
}
