{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutines-extensions/2.1.0/coroutines-extensions-2.1.0.module",
    "group": "app.cash.sqldelight",
    "module": "coroutines-extensions",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-jvm-2.1.0.jar",
          "url": "coroutines-extensions-jvm-2.1.0.jar",
          "size": 35180,
          "sha512": "81dd9f7f82734e2c9ebe1b1e06886709a1c3c7b11ac5a19445bc1cfa59e1262bb85592e38aeab0518ba431799956c9e85551003871e60eb00fa7420f2db8afef",
          "sha256": "001cc113f2a8da7173b111c0948cc7a49ae6056e083942adee582f035d3e4d69",
          "sha1": "9a0d81433c435103622778180eea43addc0f0dcf",
          "md5": "0a7cb9ee16648faf59f20404e938a287"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "async-extensions",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-jvm-2.1.0.jar",
          "url": "coroutines-extensions-jvm-2.1.0.jar",
          "size": 35180,
          "sha512": "81dd9f7f82734e2c9ebe1b1e06886709a1c3c7b11ac5a19445bc1cfa59e1262bb85592e38aeab0518ba431799956c9e85551003871e60eb00fa7420f2db8afef",
          "sha256": "001cc113f2a8da7173b111c0948cc7a49ae6056e083942adee582f035d3e4d69",
          "sha1": "9a0d81433c435103622778180eea43addc0f0dcf",
          "md5": "0a7cb9ee16648faf59f20404e938a287"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-jvm-2.1.0-sources.jar",
          "url": "coroutines-extensions-jvm-2.1.0-sources.jar",
          "size": 1955,
          "sha512": "49126acd9f3e70dfbaed031b53c1a3d6cbb175c8b6def6b091e583d920257e04483bf1f206f8d9e261d51f0036b0f58bc8603bc0a1eb2d97e336d4d3c8677758",
          "sha256": "efa521be35d10f4740cbe02ead8ea50f8087e33ff5b22a867cf3b0fe2417509f",
          "sha1": "13a08503ea244c0e710f2cd4a397a380096607de",
          "md5": "804ed11a893b6640562851ca2b0593c5"
        }
      ]
    }
  ]
}
