{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mordant-jvm-graal-ffi/3.0.2/mordant-jvm-graal-ffi-3.0.2.module",
    "group": "com.github.ajalt.mordant",
    "module": "mordant-jvm-graal-ffi",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mordant-jvm-graal-ffi-jvm.jar",
          "url": "mordant-jvm-graal-ffi-jvm-3.0.2.jar",
          "size": 35776,
          "sha512": "fb16dd69ba963a18ff75a90acc73fb5b8befec71d5eb71a9ac0093e716ba93f20f0718a07f29048b2781d9baa7b6c4df0d37acede3cc6dcbaeb40d2c8cf3416a",
          "sha256": "6dd4bebc164aeacddacc8f98e8f871e00fd21ce7bc2eb0d18230ea83bddfc86a",
          "sha1": "9cd14b9a802cd9db9f8759e49cce9ad968b637d6",
          "md5": "cced8eb5b95de65115f9675c25fce237"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant-core",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "mordant-jvm-graal-ffi-jvm.jar",
          "url": "mordant-jvm-graal-ffi-jvm-3.0.2.jar",
          "size": 35776,
          "sha512": "fb16dd69ba963a18ff75a90acc73fb5b8befec71d5eb71a9ac0093e716ba93f20f0718a07f29048b2781d9baa7b6c4df0d37acede3cc6dcbaeb40d2c8cf3416a",
          "sha256": "6dd4bebc164aeacddacc8f98e8f871e00fd21ce7bc2eb0d18230ea83bddfc86a",
          "sha1": "9cd14b9a802cd9db9f8759e49cce9ad968b637d6",
          "md5": "cced8eb5b95de65115f9675c25fce237"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mordant-jvm-graal-ffi-jvm-sources.jar",
          "url": "mordant-jvm-graal-ffi-jvm-3.0.2-sources.jar",
          "size": 7045,
          "sha512": "80e53701e2bcb0157ff8ce059fa5eaeb0eaedda2788c62927abb14d22a84cead2cf8aee37433e63993994d749c1075ae7c3883238852b6baf34adc930cf3c841",
          "sha256": "c65f7ad2867ef98621617b5d1c148312c74d2cf34db39dcabc885978accfadf1",
          "sha1": "27dec7d03ddcb1aee51b6c1c622e264bf8781196",
          "md5": "5ff547dcc61c0546b0f863b532fec526"
        }
      ]
    }
  ]
}
