{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-debug",
    "version": "1.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-debug-1.10.2.jar",
          "url": "kotlinx-coroutines-debug-1.10.2.jar",
          "size": 40495,
          "sha512": "551cdfa648b5629fc8b313b07a18d98be8953cc9787209a962b7e1eac3bfa15f8a3e3e8c2516c650176d94cd58c7b63b2e78aea8e4daa63cb930d520dd93442b",
          "sha256": "dc764af5763ca3fd74d726692459a3cd25f8a0f70fa6c71e57feb9c97e1d8ee9",
          "sha1": "62025908213f62c525b1194c57a05793384a2c78",
          "md5": "c7b23bb821b44937c28fd182adf7faf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.9"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-debug-1.10.2.jar",
          "url": "kotlinx-coroutines-debug-1.10.2.jar",
          "size": 40495,
          "sha512": "551cdfa648b5629fc8b313b07a18d98be8953cc9787209a962b7e1eac3bfa15f8a3e3e8c2516c650176d94cd58c7b63b2e78aea8e4daa63cb930d520dd93442b",
          "sha256": "dc764af5763ca3fd74d726692459a3cd25f8a0f70fa6c71e57feb9c97e1d8ee9",
          "sha1": "62025908213f62c525b1194c57a05793384a2c78",
          "md5": "c7b23bb821b44937c28fd182adf7faf9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-debug-1.10.2-sources.jar",
          "url": "kotlinx-coroutines-debug-1.10.2-sources.jar",
          "size": 16390,
          "sha512": "7864a4c149578ec06f7e299d2d994452b80c192f38d02a1c3635de74a4c9738b3181ef0d698b322181680536f9a023f76085c9504bfc68004f919e7793361545",
          "sha256": "644d735c08afb72f2dd53d68a1ab7efe88b3b33ee4f54779a38bdc3afc769cea",
          "sha1": "7b9574355e2190a988d7143d30ff76c58d9ae3f8",
          "md5": "5ce6a87c7d2760f17cd93622fe1253b1"
        }
      ]
    }
  ]
}
