{
  "formatVersion": "1.1",
  "component": {
    "group": "io.arrow-kt",
    "module": "arrow-atomic",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "arrow-atomic-metadata-2.1.2.jar",
          "url": "arrow-atomic-2.1.2.jar",
          "size": 8686,
          "sha512": "15678757ee553e176d51bff7397b6dbd733464d5a897493cb3a1648cd50db4926e7c3781c8b0f91373d0bcf78dda5765be6326be0cd4794685064f920a701328",
          "sha256": "5ab3f03f3ce6f1f5a225d31b5521bbd7ac7047d0342cb2f777dfd806ffa5402a",
          "sha1": "43ceac077f0d7aa556f3a9987971a420d0ab1e1e",
          "md5": "038f203536a26983a1f307d9b7cd87ed"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "arrow-atomic-kotlin-2.1.2-sources.jar",
          "url": "arrow-atomic-2.1.2-sources.jar",
          "size": 7145,
          "sha512": "1578fbc33ecf92039f438368352a672c2f31cd4d62084718d1d2e207c16e22a86241f28cfda95683700c1086024248c11e6f8b6a2eebdbf4f3388bb0483250fd",
          "sha256": "3f42732ad07ecd45cc7bb869871e322372c3dd7ca04fc499cdbd0bb27f98029f",
          "sha1": "c23384d572cede6a05ddb7b68e3e51cf2eb500fa",
          "md5": "7bf15d1e68a3e7c6bdec07e6d82359b1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../arrow-atomic-android/2.1.2/arrow-atomic-android-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-android",
        "version": "2.1.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../arrow-atomic-android/2.1.2/arrow-atomic-android-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-android",
        "version": "2.1.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../arrow-atomic-android/2.1.2/arrow-atomic-android-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-android",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iosarm64/2.1.2/arrow-atomic-iosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iosarm64/2.1.2/arrow-atomic-iosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iosarm64/2.1.2/arrow-atomic-iosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iossimulatorarm64/2.1.2/arrow-atomic-iossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iossimulatorarm64/2.1.2/arrow-atomic-iossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iossimulatorarm64/2.1.2/arrow-atomic-iossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iosx64/2.1.2/arrow-atomic-iosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iosx64/2.1.2/arrow-atomic-iosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-iosx64/2.1.2/arrow-atomic-iosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-iosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../arrow-atomic-js/2.1.2/arrow-atomic-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../arrow-atomic-js/2.1.2/arrow-atomic-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../arrow-atomic-js/2.1.2/arrow-atomic-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../arrow-atomic-jvm/2.1.2/arrow-atomic-jvm-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-jvm",
        "version": "2.1.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../arrow-atomic-jvm/2.1.2/arrow-atomic-jvm-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-jvm",
        "version": "2.1.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../arrow-atomic-jvm/2.1.2/arrow-atomic-jvm-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-jvm",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-linuxarm64/2.1.2/arrow-atomic-linuxarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-linuxarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-linuxarm64/2.1.2/arrow-atomic-linuxarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-linuxarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-linuxx64/2.1.2/arrow-atomic-linuxx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-linuxx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-linuxx64/2.1.2/arrow-atomic-linuxx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-linuxx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-macosarm64/2.1.2/arrow-atomic-macosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-macosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-macosarm64/2.1.2/arrow-atomic-macosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-macosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-macosarm64/2.1.2/arrow-atomic-macosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-macosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-macosx64/2.1.2/arrow-atomic-macosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-macosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-macosx64/2.1.2/arrow-atomic-macosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-macosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-macosx64/2.1.2/arrow-atomic-macosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-macosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-mingwx64/2.1.2/arrow-atomic-mingwx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-mingwx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-mingwx64/2.1.2/arrow-atomic-mingwx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-mingwx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvosarm64/2.1.2/arrow-atomic-tvosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvosarm64/2.1.2/arrow-atomic-tvosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvosarm64/2.1.2/arrow-atomic-tvosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvossimulatorarm64/2.1.2/arrow-atomic-tvossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvossimulatorarm64/2.1.2/arrow-atomic-tvossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvossimulatorarm64/2.1.2/arrow-atomic-tvossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvosx64/2.1.2/arrow-atomic-tvosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvosx64/2.1.2/arrow-atomic-tvosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-tvosx64/2.1.2/arrow-atomic-tvosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-tvosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../arrow-atomic-wasm-js/2.1.2/arrow-atomic-wasm-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-wasm-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../arrow-atomic-wasm-js/2.1.2/arrow-atomic-wasm-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-wasm-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../arrow-atomic-wasm-js/2.1.2/arrow-atomic-wasm-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-wasm-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosarm32/2.1.2/arrow-atomic-watchosarm32-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosarm32",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosarm32/2.1.2/arrow-atomic-watchosarm32-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosarm32",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosarm32/2.1.2/arrow-atomic-watchosarm32-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosarm32",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosarm64/2.1.2/arrow-atomic-watchosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosarm64/2.1.2/arrow-atomic-watchosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosarm64/2.1.2/arrow-atomic-watchosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchossimulatorarm64/2.1.2/arrow-atomic-watchossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchossimulatorarm64/2.1.2/arrow-atomic-watchossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchossimulatorarm64/2.1.2/arrow-atomic-watchossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosx64/2.1.2/arrow-atomic-watchosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosx64/2.1.2/arrow-atomic-watchosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-atomic-watchosx64/2.1.2/arrow-atomic-watchosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-atomic-watchosx64",
        "version": "2.1.2"
      }
    }
  ]
}
