{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "async-extensions",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sqldelight-async-extensions-metadata-2.1.0.jar",
          "url": "async-extensions-2.1.0.jar",
          "size": 5262,
          "sha512": "cf280c16756fe2d2f0ed3ea0e56ff98511583c7215db9c9789fbdbe927d44ac92abc2d6cd32c61b566008025a241a5ffb9fe39a5a6e35f06fd172b50fb57dac9",
          "sha256": "a69c8563d68c1e311ccf5057565edbeecba76057ae2ba7abea5dc33fbbffbb92",
          "sha1": "06682813a1c36a73d25ae23b5a908a9ae3854c02",
          "md5": "861faddf8aae85e231b6a71dfa4d6a97"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sqldelight-async-extensions-kotlin-2.1.0-sources.jar",
          "url": "async-extensions-2.1.0-sources.jar",
          "size": 3700,
          "sha512": "5e42e7d2e040461aa3d121da132b91f4d34e1934b449017c8037ad4b9f4f3da932d33e018c72c3ff0f7141af85d8b278502bf81395d5f8d1ac166ba810ea2d4c",
          "sha256": "40c20f80b7d657e6733b6ecc5f2c514ab97e103c7802edf9337bccce08259aab",
          "sha1": "bd5ae891fc296670d34497ec533cdd8e6a0c724a",
          "md5": "be48911876df4bb7dbb50ed837b27590"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativearm32/2.1.0/async-extensions-androidnativearm32-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativearm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativearm32/2.1.0/async-extensions-androidnativearm32-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativearm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativearm64/2.1.0/async-extensions-androidnativearm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativearm64/2.1.0/async-extensions-androidnativearm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativex64/2.1.0/async-extensions-androidnativex64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativex64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativex64/2.1.0/async-extensions-androidnativex64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativex64",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativex86/2.1.0/async-extensions-androidnativex86-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativex86",
        "version": "2.1.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-androidnativex86/2.1.0/async-extensions-androidnativex86-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-androidnativex86",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iosarm64/2.1.0/async-extensions-iosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iosarm64/2.1.0/async-extensions-iosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iosarm64/2.1.0/async-extensions-iosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iossimulatorarm64/2.1.0/async-extensions-iossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iossimulatorarm64/2.1.0/async-extensions-iossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iossimulatorarm64/2.1.0/async-extensions-iossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iosx64/2.1.0/async-extensions-iosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iosx64/2.1.0/async-extensions-iosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-iosx64/2.1.0/async-extensions-iosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-iosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../async-extensions-js/2.1.0/async-extensions-js-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../async-extensions-js/2.1.0/async-extensions-js-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../async-extensions-js/2.1.0/async-extensions-js-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../async-extensions-jvm/2.1.0/async-extensions-jvm-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../async-extensions-jvm/2.1.0/async-extensions-jvm-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../async-extensions-jvm/2.1.0/async-extensions-jvm-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-jvm",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-linuxarm64/2.1.0/async-extensions-linuxarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-linuxarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-linuxarm64/2.1.0/async-extensions-linuxarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-linuxarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-linuxx64/2.1.0/async-extensions-linuxx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-linuxx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-linuxx64/2.1.0/async-extensions-linuxx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-linuxx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-macosarm64/2.1.0/async-extensions-macosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-macosarm64/2.1.0/async-extensions-macosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-macosarm64/2.1.0/async-extensions-macosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-macosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-macosx64/2.1.0/async-extensions-macosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-macosx64/2.1.0/async-extensions-macosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-macosx64/2.1.0/async-extensions-macosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-macosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-mingwx64/2.1.0/async-extensions-mingwx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-mingwx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-mingwx64/2.1.0/async-extensions-mingwx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-mingwx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvosarm64/2.1.0/async-extensions-tvosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvosarm64/2.1.0/async-extensions-tvosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvosarm64/2.1.0/async-extensions-tvosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvossimulatorarm64/2.1.0/async-extensions-tvossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvossimulatorarm64/2.1.0/async-extensions-tvossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvossimulatorarm64/2.1.0/async-extensions-tvossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvosx64/2.1.0/async-extensions-tvosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvosx64/2.1.0/async-extensions-tvosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-tvosx64/2.1.0/async-extensions-tvosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-tvosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../async-extensions-wasm-js/2.1.0/async-extensions-wasm-js-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-wasm-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../async-extensions-wasm-js/2.1.0/async-extensions-wasm-js-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-wasm-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../async-extensions-wasm-js/2.1.0/async-extensions-wasm-js-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-wasm-js",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosarm32/2.1.0/async-extensions-watchosarm32-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosarm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosarm32/2.1.0/async-extensions-watchosarm32-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosarm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosarm32/2.1.0/async-extensions-watchosarm32-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosarm32",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosarm64/2.1.0/async-extensions-watchosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosarm64/2.1.0/async-extensions-watchosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosarm64/2.1.0/async-extensions-watchosarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosdevicearm64/2.1.0/async-extensions-watchosdevicearm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosdevicearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosdevicearm64/2.1.0/async-extensions-watchosdevicearm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosdevicearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosdevicearm64/2.1.0/async-extensions-watchosdevicearm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosdevicearm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchossimulatorarm64/2.1.0/async-extensions-watchossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchossimulatorarm64/2.1.0/async-extensions-watchossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchossimulatorarm64/2.1.0/async-extensions-watchossimulatorarm64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchossimulatorarm64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosx64/2.1.0/async-extensions-watchosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosx64/2.1.0/async-extensions-watchosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosx64",
        "version": "2.1.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../async-extensions-watchosx64/2.1.0/async-extensions-watchosx64-2.1.0.module",
        "group": "app.cash.sqldelight",
        "module": "async-extensions-watchosx64",
        "version": "2.1.0"
      }
    }
  ]
}
