{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lemonappdev",
    "module": "konsist",
    "version": "0.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "konsist-0.17.3.jar",
          "url": "konsist-0.17.3.jar",
          "size": 1853552,
          "sha512": "dd1d4fa989a91369726db8cdc331d1c4997c425ee86379f4d6411c67e6efa970fc80c1883bd2df2d131312b90768b6a357b1c6ba99102a5f6e8c898ae7e2bb52",
          "sha256": "ba7a5b08838c36d6b04395869680fb40110c1821aae3898d2932644eb372d744",
          "sha1": "b48221513e5fbd153a96f8ba4bc8b2eeb25e197e",
          "md5": "4eaf90d8ba8a3cebe524d5d7f37f19e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "konsist-0.17.3.jar",
          "url": "konsist-0.17.3.jar",
          "size": 1853552,
          "sha512": "dd1d4fa989a91369726db8cdc331d1c4997c425ee86379f4d6411c67e6efa970fc80c1883bd2df2d131312b90768b6a357b1c6ba99102a5f6e8c898ae7e2bb52",
          "sha256": "ba7a5b08838c36d6b04395869680fb40110c1821aae3898d2932644eb372d744",
          "sha1": "b48221513e5fbd153a96f8ba4bc8b2eeb25e197e",
          "md5": "4eaf90d8ba8a3cebe524d5d7f37f19e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "konsist-0.17.3-sources.jar",
          "url": "konsist-0.17.3-sources.jar",
          "size": 392213,
          "sha512": "5c81e11614396b733c1bd4d3c9270ef460383ff2151731cb753d3ef4eb9f25b4f56d55d2da584d43d826074ccd9df65e7c9a3ea04fba29a89432a328b3417dff",
          "sha256": "1997422b7d2faf88eb79951c9a4d2da9b10c8a3c4f6cec2d7436e2dde715d72d",
          "sha1": "a43f975f815e2058ad8d8c68013b867f7ebdb4d5",
          "md5": "8cad3cb7cde0c8f9b5dd6ffb90fff98e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "konsist-0.17.3-javadoc.jar",
          "url": "konsist-0.17.3-javadoc.jar",
          "size": 261,
          "sha512": "80e1e99b009df39865e6c700fbcd45240fcb826be655921899fe42e35ab24b1f7d1f6938fd950b018cf4ed86a9226b7a0d0d12379a054891fdc968bc3e437927",
          "sha256": "ee175454c6aaf281f7abacf6df199efe49308c8b49524d7470ecba681a2a38b5",
          "sha1": "ab94a5a432db91713c2424103c305389aac3e410",
          "md5": "14f8be3840e62c40a82f6a01ad8a9c31"
        }
      ]
    }
  ]
}
