{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.13.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.4"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.13.4.jar",
          "url": "junit-jupiter-params-5.13.4.jar",
          "size": 660823,
          "sha512": "9a020ecde5b884d2950b844fcffd5be5575434edb6bb3d2b86957133f48e45f79e770443aa07962ec340ba8da46dcb4fb6e33721c04e4ca5974c6dbe29ca47f2",
          "sha256": "3a8c6365716dbb698c0d49a05456c1e1ad05c406613c550f9dd50037872efc41",
          "sha1": "0c8930eb7fcfbed0b191703ab53f48475a75bd17",
          "md5": "a1db21cc54b627a085918626a3908c9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.13.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.13.4.jar",
          "url": "junit-jupiter-params-5.13.4.jar",
          "size": 660823,
          "sha512": "9a020ecde5b884d2950b844fcffd5be5575434edb6bb3d2b86957133f48e45f79e770443aa07962ec340ba8da46dcb4fb6e33721c04e4ca5974c6dbe29ca47f2",
          "sha256": "3a8c6365716dbb698c0d49a05456c1e1ad05c406613c550f9dd50037872efc41",
          "sha1": "0c8930eb7fcfbed0b191703ab53f48475a75bd17",
          "md5": "a1db21cc54b627a085918626a3908c9e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.13.4-javadoc.jar",
          "url": "junit-jupiter-params-5.13.4-javadoc.jar",
          "size": 400859,
          "sha512": "31dad1c8271e0ba019f2df3cbd6acd0ae386121ae7c7f04c3691a84d71e93f8c0bb16a98b95a358d9e1f018b34b32c2153b09482f6f30245d262c52a5c4d871f",
          "sha256": "a656a94f574aabb5c8533318af0554870180999ab28000cc70a8560d8cd7e994",
          "sha1": "1c63d5ff1ed88ba469751ff85dfab3bdd45f4c41",
          "md5": "3afa0355f15d283f0979cbed1ce9afae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.13.4-sources.jar",
          "url": "junit-jupiter-params-5.13.4-sources.jar",
          "size": 132372,
          "sha512": "21195c51bcf4867c936845e1c75640c29e1b64ec303a0b0d49232497da1f397bb315a0f00daea7c5b2b03fecb082a19b3fd4f3e9d720d9bcb0c32ca866b58055",
          "sha256": "173be0fd56d5befb60e4ee812eb3e1faea05181ec948299661592222aef0e352",
          "sha1": "c34ec2635caea535e60d0ff50557919a023ea3b6",
          "md5": "694c033b22433beb6c8afd94f7726174"
        }
      ]
    }
  ]
}
