{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrent-collections/2.1.0/stately-concurrent-collections-2.1.0.module",
    "group": "co.touchlab",
    "module": "stately-concurrent-collections",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-jvm-2.1.0.jar",
          "url": "stately-concurrent-collections-jvm-2.1.0.jar",
          "size": 72445,
          "sha512": "975b695194e4c44b8e6b5d54e90d68b9b3287704c3374254f2a732269c34bf8d41305db1308a19496604187330d52e02468953984f07fcfdbf125cda641ee6a5",
          "sha256": "0e0d9e7f20eaee18f7862309064c8db58ce6a3a861d8871f561546af63df1893",
          "sha1": "5c03b644537d7926a8f77e5735a8bebb55dafdcd",
          "md5": "b7acc01ab9a6662528925fb79d422dd1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-jvm-2.1.0.jar",
          "url": "stately-concurrent-collections-jvm-2.1.0.jar",
          "size": 72445,
          "sha512": "975b695194e4c44b8e6b5d54e90d68b9b3287704c3374254f2a732269c34bf8d41305db1308a19496604187330d52e02468953984f07fcfdbf125cda641ee6a5",
          "sha256": "0e0d9e7f20eaee18f7862309064c8db58ce6a3a861d8871f561546af63df1893",
          "sha1": "5c03b644537d7926a8f77e5735a8bebb55dafdcd",
          "md5": "b7acc01ab9a6662528925fb79d422dd1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stately-concurrent-collections-jvm-2.1.0-sources.jar",
          "url": "stately-concurrent-collections-jvm-2.1.0-sources.jar",
          "size": 4342,
          "sha512": "f9136afdc34d9b90c8b0f811ae21c70a49a4f7464d1bb7587ea19cbbd149d9754574369865646a77b22fb4cbf12dc08f124838fca162beea5ac13e259d917479",
          "sha256": "1507f2df766f32c7a265197ed3ad4f568e773b3e2d1f06e65b54386781df6f1a",
          "sha1": "285133d1b75d377c82036f1c773a7a2a32da5118",
          "md5": "4023abc1fef3f0666c88c93396ca9033"
        }
      ]
    }
  ]
}
