{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.91.1/core-0.91.1.module",
    "group": "io.github.pdvrieze.xmlutil",
    "module": "core",
    "version": "0.91.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmCommonApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvmcommon-0.91.1.jar",
          "url": "core-jvmcommon-0.91.1.jar",
          "size": 528947,
          "sha512": "86382841e3cf7e73b78a386ab10fd8b744bd07a6c420fce8059d011f88cdc75e27f671afd85a6c9db4a2cf282c661b28bc9ce8a00b4ee64b9463e4bd16592887",
          "sha256": "e42c177ee673fee6ce4236013733bf9940e4c62aa31d9d4252597934a62d779e",
          "sha1": "e6ccd83801b67d28341348ebc2efecbfa3e644af",
          "md5": "42285ecffda0892667c279582c374f42"
        }
      ]
    },
    {
      "name": "jvmCommonRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvmcommon-0.91.1.jar",
          "url": "core-jvmcommon-0.91.1.jar",
          "size": 528947,
          "sha512": "86382841e3cf7e73b78a386ab10fd8b744bd07a6c420fce8059d011f88cdc75e27f671afd85a6c9db4a2cf282c661b28bc9ce8a00b4ee64b9463e4bd16592887",
          "sha256": "e42c177ee673fee6ce4236013733bf9940e4c62aa31d9d4252597934a62d779e",
          "sha1": "e6ccd83801b67d28341348ebc2efecbfa3e644af",
          "md5": "42285ecffda0892667c279582c374f42"
        }
      ]
    },
    {
      "name": "jvmCommonSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-jvmcommon-0.91.1-sources.jar",
          "url": "core-jvmcommon-0.91.1-sources.jar",
          "size": 204114,
          "sha512": "d44b59f1f7f3353b7b63297ad0a35fcb2a5fa5bb1bbb8ca44a57a450fa46581f89540052cc82544174567faa5e3413187a504f68ffe1a5ee77a19154555bb390",
          "sha256": "0eeca6ec6d3eb98fda1011086cb9b81e4223d8775c3945fc222fab09484b896f",
          "sha1": "54cd814e92e74fd20241532e3413c3b6d191ad7c",
          "md5": "6f84e2e076de14963a6bb4befc6bbea5"
        }
      ]
    }
  ]
}
