{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockk-core/1.14.5/mockk-core-1.14.5.module",
    "group": "io.mockk",
    "module": "mockk-core",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-core-jvm-1.14.5.jar",
          "url": "mockk-core-jvm-1.14.5.jar",
          "size": 5094,
          "sha512": "eb248eeb67a97540030f0c014014abce641c2997cc137816aa14253daf9a4a2d426acb169a6750dc3a0f4023abaebfb56b0d7ad908edb125d036c82e63c474bf",
          "sha256": "060fffe7452e74f6e18bb9dfe1221e92c4ec0de29a84b022fb562ec6cd954691",
          "sha1": "34b1f8ab00f1b294cd17661e154258e4040ba1bd",
          "md5": "70e10c52b8b3291163f6ef49fa35de72"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-core-jvm-1.14.5.jar",
          "url": "mockk-core-jvm-1.14.5.jar",
          "size": 5094,
          "sha512": "eb248eeb67a97540030f0c014014abce641c2997cc137816aa14253daf9a4a2d426acb169a6750dc3a0f4023abaebfb56b0d7ad908edb125d036c82e63c474bf",
          "sha256": "060fffe7452e74f6e18bb9dfe1221e92c4ec0de29a84b022fb562ec6cd954691",
          "sha1": "34b1f8ab00f1b294cd17661e154258e4040ba1bd",
          "md5": "70e10c52b8b3291163f6ef49fa35de72"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-core-jvm-1.14.5-sources.jar",
          "url": "mockk-core-jvm-1.14.5-sources.jar",
          "size": 3343,
          "sha512": "7491507d27f0655a867e1c2ff8981c59ea3736f8c8e9c1f478499e3d1f5c06827c71db2496b7a2cf00a93f5094033243d359b52b855101815c7dd7c5ee6877eb",
          "sha256": "f2ff944144a5048770574271c6cd874fb8c8726ed0449b8507afd93b4b170249",
          "sha1": "3196d024da758923e3fc9ff2ea831a12ec0192ba",
          "md5": "e0e1d89a03c81641058a73e49d4e86fb"
        }
      ]
    }
  ]
}
