{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "native-gradle-plugin",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-gradle-plugin-0.11.0.jar",
          "url": "native-gradle-plugin-0.11.0.jar",
          "size": 123063,
          "sha512": "f1612f0d8b41dec5f761adcbb319189d0797fc637c851930a27abb0639b45adb723a55f03445b87a8dd8ef9e0558fca13ca504784953de648c25300114a07bf2",
          "sha256": "81e92dbe225c3bdbec28bf0f47882e9d5fdff671cc79367044ea4d3d0f033136",
          "sha1": "f3a8d9804c2afcd921f0115f0c59d916bdae9014",
          "md5": "322a93d75e6e8c802ba2dec5a001b85f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.graalvm.buildtools",
          "module": "utils",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.graalvm.buildtools",
          "module": "graalvm-reachability-metadata",
          "version": {
            "requires": "0.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "native-gradle-plugin-0.11.0.jar",
          "url": "native-gradle-plugin-0.11.0.jar",
          "size": 123063,
          "sha512": "f1612f0d8b41dec5f761adcbb319189d0797fc637c851930a27abb0639b45adb723a55f03445b87a8dd8ef9e0558fca13ca504784953de648c25300114a07bf2",
          "sha256": "81e92dbe225c3bdbec28bf0f47882e9d5fdff671cc79367044ea4d3d0f033136",
          "sha1": "f3a8d9804c2afcd921f0115f0c59d916bdae9014",
          "md5": "322a93d75e6e8c802ba2dec5a001b85f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-gradle-plugin-0.11.0-javadoc.jar",
          "url": "native-gradle-plugin-0.11.0-javadoc.jar",
          "size": 275884,
          "sha512": "e795ab6aa5621e733b03fe97381359793da05bf1a10f3634683b3dd3c60c61302494da1f27911e8d9154bda11a2541ed305ebaa457ef744d12aed657598f1579",
          "sha256": "2b0d51891bfbd4a0b5214a0fe42481b7e362450ea38bcd22a165091f0f4c0b00",
          "sha1": "13279112c569072c4bd23b24766580797a217983",
          "md5": "0ad2884ef10ed9480d3356aacea91d2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-gradle-plugin-0.11.0-sources.jar",
          "url": "native-gradle-plugin-0.11.0-sources.jar",
          "size": 96934,
          "sha512": "3c0c574b4f5eefc31245ba1bf6dc4cdda2f0f1117939dd8993e98114f62815d8aa7fc220ea97d67adf8144fdf2c6f2e54c5f5547101513eeb195a238a9711b0d",
          "sha256": "8a8115d03e770b6527845fb34480a970495e6d81f6f414e19b8f3b8ecf516e1a",
          "sha1": "e86cdde893cb6732589d9f81e9b1e2d4aedee540",
          "md5": "aa4f99ebfc934d5df843b5e829a1a1b8"
        }
      ]
    }
  ]
}
