{
  "formatVersion": "1.1",
  "component": {
    "url": "../../serialization/0.91.1/serialization-0.91.1.module",
    "group": "io.github.pdvrieze.xmlutil",
    "module": "serialization",
    "version": "0.91.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "core",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-jvm-0.91.1.jar",
          "url": "serialization-jvm-0.91.1.jar",
          "size": 584447,
          "sha512": "ee564cb451042b550774714fb5f7642520eed88bf482957650ebc3c1aa0c10185acf12c5d93931899175f722c4d733d5501375ed28d0a95e0d9d8de91348802d",
          "sha256": "5b4b1fb39e78913b6626d344c5de8f3a220c88493e4a29f68957f8711a106206",
          "sha1": "83e0aa003acda2ef44349b5214ab982d9eea84ea",
          "md5": "917b3330bd65e4b2b3b3ce3ad8b5cf55"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "core",
          "version": {
            "requires": "0.91.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "core",
          "version": {
            "requires": "0.91.1"
          }
        }
      ],
      "files": [
        {
          "name": "serialization-jvm-0.91.1.jar",
          "url": "serialization-jvm-0.91.1.jar",
          "size": 584447,
          "sha512": "ee564cb451042b550774714fb5f7642520eed88bf482957650ebc3c1aa0c10185acf12c5d93931899175f722c4d733d5501375ed28d0a95e0d9d8de91348802d",
          "sha256": "5b4b1fb39e78913b6626d344c5de8f3a220c88493e4a29f68957f8711a106206",
          "sha1": "83e0aa003acda2ef44349b5214ab982d9eea84ea",
          "md5": "917b3330bd65e4b2b3b3ce3ad8b5cf55"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "serialization-jvm-0.91.1-sources.jar",
          "url": "serialization-jvm-0.91.1-sources.jar",
          "size": 127885,
          "sha512": "deff7e95e565aa9730f270a134328a76d434a6c9a8fadbc6d49ae2d1ae5a9c5b6d840aa9b53e0f4122c3fb2484b75af6e6d3c9abb07c8f736196d118d35c5abd",
          "sha256": "3faa6933687e62e9b3c11adeb94365a6d0d04df9fb80557b0f51af5c3ec948e0",
          "sha1": "23afe023bd6e67106e3deb61ea1a988bdd421c9f",
          "md5": "74d431422baf4de1d0d1d5a399b1801b"
        }
      ]
    }
  ]
}
