{
  "formatVersion": "1.1",
  "component": {
    "url": "../../colormath/3.6.0/colormath-3.6.0.module",
    "group": "com.github.ajalt.colormath",
    "module": "colormath",
    "version": "3.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "colormath-jvm.jar",
          "url": "colormath-jvm-3.6.0.jar",
          "size": 352563,
          "sha512": "392c97e63581e6847795201fdf299c0cc602035e3cc68f5b8f3518a1858e0147aab140dc3f9d01f853b883891741eb770b7d66966c7ee7b0e9ab6b2016048e22",
          "sha256": "59f741adfe62053066782d8b1a45afd06685a4bc64b33277e54876b993ed885c",
          "sha1": "d5593e3f07b2447bec0b17f5cb7141a0f0de9688",
          "md5": "6a279b2713acb5c7ffb5e60803bf2841"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "colormath-jvm.jar",
          "url": "colormath-jvm-3.6.0.jar",
          "size": 352563,
          "sha512": "392c97e63581e6847795201fdf299c0cc602035e3cc68f5b8f3518a1858e0147aab140dc3f9d01f853b883891741eb770b7d66966c7ee7b0e9ab6b2016048e22",
          "sha256": "59f741adfe62053066782d8b1a45afd06685a4bc64b33277e54876b993ed885c",
          "sha1": "d5593e3f07b2447bec0b17f5cb7141a0f0de9688",
          "md5": "6a279b2713acb5c7ffb5e60803bf2841"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "colormath-jvm-sources.jar",
          "url": "colormath-jvm-3.6.0-sources.jar",
          "size": 68150,
          "sha512": "dd0cfdf16665437b044d43e0b758e7e83618ab6a558de0567cfb4e1d84fb4c39c66344ff56539b48dc8bc5e8d31ae4fc5eb4cb2573eccc65e47fc759e76b986f",
          "sha256": "cd4baaaa928f21ec45b0cbf78f7071a94be9830bf0e3ed8f320e851f47b32864",
          "sha1": "a0f43a207f4b991240cea93b9be5845e1cdcfde2",
          "md5": "15508a4f8879465963a985259b8f24d3"
        }
      ]
    }
  ]
}
