{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-shared/6.0.3/kotest-assertions-shared-6.0.3.module",
    "group": "io.kotest",
    "module": "kotest-assertions-shared",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-6.0.3.jar",
          "url": "kotest-assertions-shared-jvm-6.0.3.jar",
          "size": 66282,
          "sha512": "51e1a8579e9921b660f2754769e273d4b16e2f218ba071dd48cf90f068fbd05fab818252bf54083c96af21bec1c785f3abd97f427c222a7a34950a9e8079af74",
          "sha256": "5f02376832e9283a9d6ee2c5ba8950ac66ef9516a5c6a111fcdda3b2978373e1",
          "sha1": "2c4264d908c79c96e572cca8d5ac55456f4d123e",
          "md5": "d1f54cceaa74e38a385e13a9bbbba443"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-6.0.3.jar",
          "url": "kotest-assertions-shared-jvm-6.0.3.jar",
          "size": 66282,
          "sha512": "51e1a8579e9921b660f2754769e273d4b16e2f218ba071dd48cf90f068fbd05fab818252bf54083c96af21bec1c785f3abd97f427c222a7a34950a9e8079af74",
          "sha256": "5f02376832e9283a9d6ee2c5ba8950ac66ef9516a5c6a111fcdda3b2978373e1",
          "sha1": "2c4264d908c79c96e572cca8d5ac55456f4d123e",
          "md5": "d1f54cceaa74e38a385e13a9bbbba443"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-shared-jvm-6.0.3-sources.jar",
          "url": "kotest-assertions-shared-jvm-6.0.3-sources.jar",
          "size": 12885,
          "sha512": "fb3b5d78b7b23f4e749bdae8099983b9b2bbb85376adea8c7189b20e73acce21217ae8d37de115590bfaf6e3ffe7314e4527582625fe79463577ecc753197075",
          "sha256": "72adc488a86aa1b41f964c3c77fa6b392dae7b8f2d915fc068f193e6773c93fe",
          "sha1": "874b9a189437945b3fc24d3674a5bbff6afa5a29",
          "md5": "6f8364f32e2e8299c560955dc1746255"
        }
      ]
    }
  ]
}
