{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockk-agent-api/1.14.5/mockk-agent-api-1.14.5.module",
    "group": "io.mockk",
    "module": "mockk-agent-api",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-api-jvm-1.14.5.jar",
          "url": "mockk-agent-api-jvm-1.14.5.jar",
          "size": 49878,
          "sha512": "d538f4cf784e492e79f129cf096745294fcfa1fec795ba3367797889d54181cd6def714c97fb6b17e0fc7aa9f49c549f3f40152851ee6d18457e9a8708c07b92",
          "sha256": "a919a8fec03dfb0c084cb43dafcebe2dd9351431c7a08c2fc8147037de1d06b7",
          "sha1": "4e92555e63eb400f5d37b344ed9130a899aba1bb",
          "md5": "02eb763859f3eb4c6b9f9781b5328c10"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-agent-api-jvm-1.14.5.jar",
          "url": "mockk-agent-api-jvm-1.14.5.jar",
          "size": 49878,
          "sha512": "d538f4cf784e492e79f129cf096745294fcfa1fec795ba3367797889d54181cd6def714c97fb6b17e0fc7aa9f49c549f3f40152851ee6d18457e9a8708c07b92",
          "sha256": "a919a8fec03dfb0c084cb43dafcebe2dd9351431c7a08c2fc8147037de1d06b7",
          "sha1": "4e92555e63eb400f5d37b344ed9130a899aba1bb",
          "md5": "02eb763859f3eb4c6b9f9781b5328c10"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-agent-api-jvm-1.14.5-sources.jar",
          "url": "mockk-agent-api-jvm-1.14.5-sources.jar",
          "size": 12679,
          "sha512": "26127f11eb712869373e7bdf392e71e447a1fdd6ba27ebd5f4c7f4b03fec21e9cf57ee0426feb7be6d1ef26a8c05591d9aacc060b41b24ff61de3ca06fc1ef66",
          "sha256": "b88f7e2e15058764ed113d7426e3c9700b7fecbe0840f80ca4d5d3a3f5edaf64",
          "sha1": "0f2f66886939fad2188c7798aacccd74690be758",
          "md5": "21194017c3a7afdbc27f8a035ad726e0"
        }
      ]
    }
  ]
}
