{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kotest.extensions",
    "module": "kotest-assertions-arrow",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-arrow-metadata-2.0.0.jar",
          "url": "kotest-assertions-arrow-2.0.0.jar",
          "size": 6683,
          "sha512": "ae8181a1ddd7da98f771f31d3fe3c3e9f655e0f977fab4253d838525f57160acde388f5893d46cdd5fc8b4f3dbea0b05f487d34d72e0f0d8d9f1a821ca147975",
          "sha256": "fe974d8a46d024f74cd12955dae8f2a6fcd6c1f42eaeac517effdbecc4d9f3e9",
          "sha1": "7223153a46c70ea4ecd2dd988e499559da99f8f9",
          "md5": "18d860f5ecc5377eee5ce215b604b9a2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotest-assertions-arrow-kotlin-2.0.0-sources.jar",
          "url": "kotest-assertions-arrow-2.0.0-sources.jar",
          "size": 5894,
          "sha512": "edb8c394e460e774481455161e5c61e9d13a494fecacbbe97074d98447b0a3544ef84c6c135134d5b6ecbcbab97f1c927d9f720dcdb885361da3aabea2d4e464",
          "sha256": "fab8024b4734a14401c6a662dbb78e5084ebd00507a1af7a9d04c2d3c7286cfc",
          "sha1": "5d406b55f191ccf62a8cb1c909a0ee1dc9ce0499",
          "md5": "472957b7a484184aec27ff805ac89af3"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosarm64/2.0.0/kotest-assertions-arrow-iosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosarm64/2.0.0/kotest-assertions-arrow-iosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosarm64/2.0.0/kotest-assertions-arrow-iosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iossimulatorarm64/2.0.0/kotest-assertions-arrow-iossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iossimulatorarm64/2.0.0/kotest-assertions-arrow-iossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iossimulatorarm64/2.0.0/kotest-assertions-arrow-iossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosx64/2.0.0/kotest-assertions-arrow-iosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosx64/2.0.0/kotest-assertions-arrow-iosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-iosx64/2.0.0/kotest-assertions-arrow-iosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-iosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/2.0.0/kotest-assertions-arrow-js-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/2.0.0/kotest-assertions-arrow-js-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-js/2.0.0/kotest-assertions-arrow-js-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-js",
        "version": "2.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/2.0.0/kotest-assertions-arrow-jvm-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-jvm",
        "version": "2.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/2.0.0/kotest-assertions-arrow-jvm-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-jvm",
        "version": "2.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-jvm/2.0.0/kotest-assertions-arrow-jvm-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-jvm",
        "version": "2.0.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-linuxx64/2.0.0/kotest-assertions-arrow-linuxx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-linuxx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-linuxx64/2.0.0/kotest-assertions-arrow-linuxx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-linuxx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosarm64/2.0.0/kotest-assertions-arrow-macosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-macosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosarm64/2.0.0/kotest-assertions-arrow-macosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-macosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosarm64/2.0.0/kotest-assertions-arrow-macosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-macosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosx64/2.0.0/kotest-assertions-arrow-macosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-macosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosx64/2.0.0/kotest-assertions-arrow-macosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-macosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-macosx64/2.0.0/kotest-assertions-arrow-macosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-macosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-mingwx64/2.0.0/kotest-assertions-arrow-mingwx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-mingwx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-mingwx64/2.0.0/kotest-assertions-arrow-mingwx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-mingwx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosarm64/2.0.0/kotest-assertions-arrow-tvosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosarm64/2.0.0/kotest-assertions-arrow-tvosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosarm64/2.0.0/kotest-assertions-arrow-tvosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvossimulatorarm64/2.0.0/kotest-assertions-arrow-tvossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvossimulatorarm64/2.0.0/kotest-assertions-arrow-tvossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvossimulatorarm64/2.0.0/kotest-assertions-arrow-tvossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosx64/2.0.0/kotest-assertions-arrow-tvosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosx64/2.0.0/kotest-assertions-arrow-tvosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-tvosx64/2.0.0/kotest-assertions-arrow-tvosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-tvosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm32/2.0.0/kotest-assertions-arrow-watchosarm32-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosarm32",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm32/2.0.0/kotest-assertions-arrow-watchosarm32-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosarm32",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm32/2.0.0/kotest-assertions-arrow-watchosarm32-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosarm32",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm64/2.0.0/kotest-assertions-arrow-watchosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm64/2.0.0/kotest-assertions-arrow-watchosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosarm64/2.0.0/kotest-assertions-arrow-watchosarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchossimulatorarm64/2.0.0/kotest-assertions-arrow-watchossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchossimulatorarm64/2.0.0/kotest-assertions-arrow-watchossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchossimulatorarm64/2.0.0/kotest-assertions-arrow-watchossimulatorarm64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchossimulatorarm64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosx64/2.0.0/kotest-assertions-arrow-watchosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosx64/2.0.0/kotest-assertions-arrow-watchosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosx64",
        "version": "2.0.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotest-assertions-arrow-watchosx64/2.0.0/kotest-assertions-arrow-watchosx64-2.0.0.module",
        "group": "io.kotest.extensions",
        "module": "kotest-assertions-arrow-watchosx64",
        "version": "2.0.0"
      }
    }
  ]
}
