{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sql-psi",
    "module": "environment",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "environment-0.5.2.jar",
          "url": "environment-0.5.2.jar",
          "size": 15678,
          "sha512": "b6fd023158eaad7e3b673e872583bdf9a69a48ece573cd07d53a3537fa8b47a3e92c0c33141d1223b2fbebccb2b5df151908eb1d93912e10f96d947196265efa",
          "sha256": "5825a1e1a752874839dd8990fca34980dd7afb2e17b42162fd3462959eee234f",
          "sha1": "5160492dd893f509d390e8fd894f6e873e83c29c",
          "md5": "b40f15231114132a22267b6c7d6ba0ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sql-psi",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "environment-0.5.2.jar",
          "url": "environment-0.5.2.jar",
          "size": 15678,
          "sha512": "b6fd023158eaad7e3b673e872583bdf9a69a48ece573cd07d53a3537fa8b47a3e92c0c33141d1223b2fbebccb2b5df151908eb1d93912e10f96d947196265efa",
          "sha256": "5825a1e1a752874839dd8990fca34980dd7afb2e17b42162fd3462959eee234f",
          "sha1": "5160492dd893f509d390e8fd894f6e873e83c29c",
          "md5": "b40f15231114132a22267b6c7d6ba0ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "environment-0.5.2-sources.jar",
          "url": "environment-0.5.2-sources.jar",
          "size": 3363,
          "sha512": "bb343b3f84460bc42f02eae1f49ab709f854bdfb9c908556490875d7fe3caf76881fc6f45ab0f51c7285e3622b750ba7eaf1e65e6665f753713ee0b0b9d77344",
          "sha256": "70d11e3fd168a3643ee668d8e2a2a7dc7d9a893c6b3df542b1db1285d0985215",
          "sha1": "8ae729233db265c535c209dca5e627e6ec79578d",
          "md5": "547718693da26f9a6bf00326e4cfcccb"
        }
      ]
    }
  ]
}
