{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinpoet/1.18.1/kotlinpoet-1.18.1.module",
    "group": "com.squareup",
    "module": "kotlinpoet",
    "version": "1.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-jvm-1.18.1.jar",
          "url": "kotlinpoet-jvm-1.18.1.jar",
          "size": 343196,
          "sha512": "f99a361e816f9b5158d2758809ab7024004ace25b06198aa7aed58756f1a468d258c2ad4528874d64984a67987833811e83d0add1b2a1b872632cb78c913ea86",
          "sha256": "b3ec7ef1c27346d188c113159bcf6477a236b340d3243e524f7c454e3922c564",
          "sha1": "c4143e9d675aac41f47ceb4e7886d801010bd0c8",
          "md5": "2582bcc51e690d136f6952a179331053"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-jvm-1.18.1.jar",
          "url": "kotlinpoet-jvm-1.18.1.jar",
          "size": 343196,
          "sha512": "f99a361e816f9b5158d2758809ab7024004ace25b06198aa7aed58756f1a468d258c2ad4528874d64984a67987833811e83d0add1b2a1b872632cb78c913ea86",
          "sha256": "b3ec7ef1c27346d188c113159bcf6477a236b340d3243e524f7c454e3922c564",
          "sha1": "c4143e9d675aac41f47ceb4e7886d801010bd0c8",
          "md5": "2582bcc51e690d136f6952a179331053"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinpoet-jvm-1.18.1-sources.jar",
          "url": "kotlinpoet-jvm-1.18.1-sources.jar",
          "size": 87579,
          "sha512": "721e4689fc57d726e9a44f5c063f2772981770b33baada64a6b9f4360be716c2ae809f5f2a6073a233d6fb5014ff8a889d82d0bf250cc108bcc2dc2666ca1876",
          "sha256": "44dffa4e964caadd58db19c8e9cc2c1cddf016eaa5d14722dee0721c1b2c97cd",
          "sha1": "03d473e52ae6094cc94a1b9cf4285118216b0ca4",
          "md5": "65edad5fda1cbaeefeab7cca7af2049d"
        }
      ]
    }
  ]
}
