{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "graalvm-reachability-metadata",
    "version": "0.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graalvm-reachability-metadata-0.11.0.jar",
          "url": "graalvm-reachability-metadata-0.11.0.jar",
          "size": 26623,
          "sha512": "416df44b12fba1a52251423fd2bb8fb07f9dc0e657893f184935bce4d4dfaf3bd8c358b6077f194c4ad5dd8fa0a664d2f04f10e92b679cf33418a15e1afff717",
          "sha256": "382eded323db5a3588bf34072397aa64530821a67e91f4e2738593b84d508301",
          "sha1": "0ea9ee6ab24f4811e7704a3005b2cfdfdc61ec8a",
          "md5": "51562a48399a1a3832ab9b68377e8755"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.openjson",
          "module": "openjson",
          "version": {
            "requires": "1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "graalvm-reachability-metadata-0.11.0.jar",
          "url": "graalvm-reachability-metadata-0.11.0.jar",
          "size": 26623,
          "sha512": "416df44b12fba1a52251423fd2bb8fb07f9dc0e657893f184935bce4d4dfaf3bd8c358b6077f194c4ad5dd8fa0a664d2f04f10e92b679cf33418a15e1afff717",
          "sha256": "382eded323db5a3588bf34072397aa64530821a67e91f4e2738593b84d508301",
          "sha1": "0ea9ee6ab24f4811e7704a3005b2cfdfdc61ec8a",
          "md5": "51562a48399a1a3832ab9b68377e8755"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graalvm-reachability-metadata-0.11.0-javadoc.jar",
          "url": "graalvm-reachability-metadata-0.11.0-javadoc.jar",
          "size": 144314,
          "sha512": "b8a979e7a16724c2cb99cccb4224def86a5170b4a46fc4f993ef4bcbaee320bcf50e9d5d85287b313d14996a1bcaff9c2dd310892e6cb5399252e75961ff6f9d",
          "sha256": "a6145d8506de2a404778a3a4782b4345fda740cef4d7091dbb420c9c58947ee7",
          "sha1": "b2139eeca962feccc0219e83750b810f2cb57903",
          "md5": "c8935232926df1ded28fd82b04d8c2cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graalvm-reachability-metadata-0.11.0-sources.jar",
          "url": "graalvm-reachability-metadata-0.11.0-sources.jar",
          "size": 29079,
          "sha512": "ae7ae30df94c1c061f2a8d7e20ac7a35fd2ada815b8b11bc5bb7736a455e14a1c1a2da7aa67e98c5b03daa75fd2271b04a41cba81317165c49779dd87bad23fb",
          "sha256": "99c1f07ef73490803d611eba622679f4e5ca16e2b4e7d1667e307ece3d244ba2",
          "sha1": "c7e502c6d796b2818b5fc38a56446512f8d1511a",
          "md5": "41c1f0577cf949fcdb7df93601572b63"
        }
      ]
    }
  ]
}
