{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.13.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.13.4"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.13.4.jar",
          "url": "junit-jupiter-api-5.13.4.jar",
          "size": 240237,
          "sha512": "6e6c1d1247b5aa99649e6cc2f8ea8f0f3720f2a141682b152eed878b1b807b4d6348741a4e616d695f92a80d327ef4e857c48cde13b9668fa75f1301202ec652",
          "sha256": "d1bb81abfd9e03418306b4e6a3390c8db52c58372e749c2980ac29f0c08278f1",
          "sha1": "2817f736551fe4949b79924715ef6f594ee072f4",
          "md5": "d9981621212d598a4ba380342094c92f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.13.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.13.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.13.4.jar",
          "url": "junit-jupiter-api-5.13.4.jar",
          "size": 240237,
          "sha512": "6e6c1d1247b5aa99649e6cc2f8ea8f0f3720f2a141682b152eed878b1b807b4d6348741a4e616d695f92a80d327ef4e857c48cde13b9668fa75f1301202ec652",
          "sha256": "d1bb81abfd9e03418306b4e6a3390c8db52c58372e749c2980ac29f0c08278f1",
          "sha1": "2817f736551fe4949b79924715ef6f594ee072f4",
          "md5": "d9981621212d598a4ba380342094c92f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.13.4-javadoc.jar",
          "url": "junit-jupiter-api-5.13.4-javadoc.jar",
          "size": 931322,
          "sha512": "6b93f99af2f32cf00cd3e8e2ad7a4534944e8268370d35680dc274b60476e605e2ceab5083232fe03276e1ae27c9e3219e8de8d8765907eaa4113d7eb15688d2",
          "sha256": "e105d948b9cd893b8957e36f44977f0fae54f5ab7b092f7eb5eddf91009cef47",
          "sha1": "ab722a14502c0559068df9b49363afc0edb4975d",
          "md5": "248f262695d0107f9d85a1ff6fc7c1b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.13.4-sources.jar",
          "url": "junit-jupiter-api-5.13.4-sources.jar",
          "size": 243073,
          "sha512": "8c53c41c16e63a7f2eb3655834df0fccca26c8d62b55a4569f425b94ecd1be8ec1a6c4690cba2d146655a996cb68a7934e876b921e19041cf53a8fcf3fd6a063",
          "sha256": "c6d33325ffa47307b795c13cb227f002417eebf0927e40487159c53938f2793e",
          "sha1": "d6de55e11ea559f5a11b6718abdc728b6c1c385c",
          "md5": "7c8a4ce13c5f9556cf0685ac923f8685"
        }
      ]
    }
  ]
}
