{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockk/1.14.5/mockk-1.14.5.module",
    "group": "io.mockk",
    "module": "mockk",
    "version": "1.14.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-core",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-jvm-1.14.5.jar",
          "url": "mockk-jvm-1.14.5.jar",
          "size": 547075,
          "sha512": "0ecabd3532e22460d48be78fa1f00bc98e1d5a14993abf348b85ceb60d28ba54ec23d74e767d769bd2e1f14d440d6c1024074d496d4b196dcfb1c4475c7fd80f",
          "sha256": "74deb86cbab6871a3e4d0f97ba8eacbdae7aacd7537f142bcb083590465a6219",
          "sha1": "d4d0a39318eb6fcf726187004fb037bccdde67f8",
          "md5": "c614bf67de453a670461802bc1ca7d8a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.mockk",
          "module": "mockk-dsl",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-api",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-core",
          "version": {
            "requires": "1.14.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-jvm-1.14.5.jar",
          "url": "mockk-jvm-1.14.5.jar",
          "size": 547075,
          "sha512": "0ecabd3532e22460d48be78fa1f00bc98e1d5a14993abf348b85ceb60d28ba54ec23d74e767d769bd2e1f14d440d6c1024074d496d4b196dcfb1c4475c7fd80f",
          "sha256": "74deb86cbab6871a3e4d0f97ba8eacbdae7aacd7537f142bcb083590465a6219",
          "sha1": "d4d0a39318eb6fcf726187004fb037bccdde67f8",
          "md5": "c614bf67de453a670461802bc1ca7d8a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-jvm-1.14.5-sources.jar",
          "url": "mockk-jvm-1.14.5-sources.jar",
          "size": 82481,
          "sha512": "687a2bd0a31d03fff786433cdda9d55dcd4ea01a6152a3e8ec972b609446a5ae3df7dca0fddd4c1795e29e2cb081a762ce579616ad3d4d9b407d5a2462b33c58",
          "sha256": "b2931c01a2e19e3831c161a3b3021173f3e56dd482e94dcccecee9ad57754768",
          "sha1": "b458e8ad163a46200656871a1e62ec11f746dd21",
          "md5": "70065fba7989320b04e02fcceb5d9f6f"
        }
      ]
    }
  ]
}
