{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/4.1.1/koin-core-4.1.1.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-4.1.1.jar",
          "url": "koin-core-jvm-4.1.1.jar",
          "size": 399319,
          "sha512": "afafebb423e6f877049475d86f63eec8faa400a3ecd6985077c7ebe031344c1281deca072f02b21a94b6ee3e2d93dc1401de0d15f1a0bdf3cea076606343447b",
          "sha256": "90a8e98c0de5351325804db39a2154ab283503a6d92981609da3dcc16b0d15ca",
          "sha1": "c3347d7e3dbce55435cb9141956ec641b283cbbb",
          "md5": "79d4fb7bbb3a6f260988ab2d5faa9ccf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-4.1.1.jar",
          "url": "koin-core-jvm-4.1.1.jar",
          "size": 399319,
          "sha512": "afafebb423e6f877049475d86f63eec8faa400a3ecd6985077c7ebe031344c1281deca072f02b21a94b6ee3e2d93dc1401de0d15f1a0bdf3cea076606343447b",
          "sha256": "90a8e98c0de5351325804db39a2154ab283503a6d92981609da3dcc16b0d15ca",
          "sha1": "c3347d7e3dbce55435cb9141956ec641b283cbbb",
          "md5": "79d4fb7bbb3a6f260988ab2d5faa9ccf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koin-core-jvm-4.1.1-sources.jar",
          "url": "koin-core-jvm-4.1.1-sources.jar",
          "size": 77123,
          "sha512": "75e5cac6b52b33003033b82f6ce4693455f11cec7e5c14a95c77aa6a36335f5f6d212e6addce31b3def7466b7928cf87446b992fb61a9777d3cedbc2aa7c2699",
          "sha256": "307728db5396370a06168ac013d8d4e5ddc460f8a0a8c2d85561527c3972cc63",
          "sha1": "1c9ff2551575cc1996e6e25c5695663e299cf6ca",
          "md5": "87fcd1206998c046a34e7a395c2ae0a9"
        }
      ]
    }
  ]
}
