{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "migrations",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "migrations-2.1.0.jar",
          "url": "migrations-2.1.0.jar",
          "size": 16804,
          "sha512": "3d78b2731facde5c6722a1297947b441812bcde4d07d2ce61255687b8e443a6f3b0ca8bdf0c8fc55861f76698007808e3aedd5ec60c7af6cbca0e922cfdae319",
          "sha256": "51d9dd68571e493f30bbc002bef9e01f83be66e727097b2dea943a99a4974b18",
          "sha1": "f149133e3db04c008e84735b4f48fcc526d2b90b",
          "md5": "b262f1023923b35c044676a0bc1aab16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "com.jetbrains.intellij.platform",
              "module": "wsl-impl"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "com.jetbrains.infra",
              "module": "*"
            },
            {
              "group": "org.jetbrains.teamcity",
              "module": "*"
            },
            {
              "group": "ai.grazie.spell",
              "module": "*"
            },
            {
              "group": "ai.grazie.model",
              "module": "*"
            },
            {
              "group": "ai.grazie.utils",
              "module": "*"
            },
            {
              "group": "ai.grazie.nlp",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "migrations-2.1.0.jar",
          "url": "migrations-2.1.0.jar",
          "size": 16804,
          "sha512": "3d78b2731facde5c6722a1297947b441812bcde4d07d2ce61255687b8e443a6f3b0ca8bdf0c8fc55861f76698007808e3aedd5ec60c7af6cbca0e922cfdae319",
          "sha256": "51d9dd68571e493f30bbc002bef9e01f83be66e727097b2dea943a99a4974b18",
          "sha1": "f149133e3db04c008e84735b4f48fcc526d2b90b",
          "md5": "b262f1023923b35c044676a0bc1aab16"
        }
      ]
    }
  ]
}
