{
  "formatVersion": "1.1",
  "component": {
    "group": "io.arrow-kt",
    "module": "arrow-annotations",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "arrow-annotations-metadata-2.1.2.jar",
          "url": "arrow-annotations-2.1.2.jar",
          "size": 3387,
          "sha512": "a1be354b8a856c02e8e2d4cccd19426d6a44986e6142c92e0991270d7feeb680863100115b06fde788dbea7bda22ee2dd4f51eb533bb82712843d6b87fcb8ba8",
          "sha256": "a273ac054c9471ee33f21989f5f591ddc9daeee65f92687c34dd5486897d6b63",
          "sha1": "91c59af6d4f8cb7be389caaf934634d920bd5d87",
          "md5": "9f99e5111b2dc7468f2d2ba99a4f37e5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "arrow-annotations-kotlin-2.1.2-sources.jar",
          "url": "arrow-annotations-2.1.2-sources.jar",
          "size": 1531,
          "sha512": "49bc9c17042bb0b6aabdf808d96b5e50e21473afcf0afbd68d6801dd68309df080c4493edea4c80122dd7cf41b6b8fa0b2e0e1a26604f2254bc42624fff5a915",
          "sha256": "a9aaa1edbeae86ba91d78a0bf7430415c9419b131dc7d0d58c8200bf403ff0eb",
          "sha1": "81a44e1c752596994d69ef106713b94f09ff202a",
          "md5": "57bfa62f57b7114a02769474845e07f8"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../arrow-annotations-android/2.1.2/arrow-annotations-android-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-android",
        "version": "2.1.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../arrow-annotations-android/2.1.2/arrow-annotations-android-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-android",
        "version": "2.1.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../arrow-annotations-android/2.1.2/arrow-annotations-android-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-android",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iosarm64/2.1.2/arrow-annotations-iosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iosarm64/2.1.2/arrow-annotations-iosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iosarm64/2.1.2/arrow-annotations-iosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iossimulatorarm64/2.1.2/arrow-annotations-iossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iossimulatorarm64/2.1.2/arrow-annotations-iossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iossimulatorarm64/2.1.2/arrow-annotations-iossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iosx64/2.1.2/arrow-annotations-iosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iosx64/2.1.2/arrow-annotations-iosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-iosx64/2.1.2/arrow-annotations-iosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-iosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../arrow-annotations-js/2.1.2/arrow-annotations-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../arrow-annotations-js/2.1.2/arrow-annotations-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../arrow-annotations-js/2.1.2/arrow-annotations-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../arrow-annotations-jvm/2.1.2/arrow-annotations-jvm-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-jvm",
        "version": "2.1.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../arrow-annotations-jvm/2.1.2/arrow-annotations-jvm-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-jvm",
        "version": "2.1.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../arrow-annotations-jvm/2.1.2/arrow-annotations-jvm-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-jvm",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-linuxarm64/2.1.2/arrow-annotations-linuxarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-linuxarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-linuxarm64/2.1.2/arrow-annotations-linuxarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-linuxarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-linuxx64/2.1.2/arrow-annotations-linuxx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-linuxx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-linuxx64/2.1.2/arrow-annotations-linuxx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-linuxx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-macosarm64/2.1.2/arrow-annotations-macosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-macosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-macosarm64/2.1.2/arrow-annotations-macosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-macosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-macosarm64/2.1.2/arrow-annotations-macosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-macosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-macosx64/2.1.2/arrow-annotations-macosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-macosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-macosx64/2.1.2/arrow-annotations-macosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-macosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-macosx64/2.1.2/arrow-annotations-macosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-macosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-mingwx64/2.1.2/arrow-annotations-mingwx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-mingwx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-mingwx64/2.1.2/arrow-annotations-mingwx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-mingwx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvosarm64/2.1.2/arrow-annotations-tvosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvosarm64/2.1.2/arrow-annotations-tvosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvosarm64/2.1.2/arrow-annotations-tvosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvossimulatorarm64/2.1.2/arrow-annotations-tvossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvossimulatorarm64/2.1.2/arrow-annotations-tvossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvossimulatorarm64/2.1.2/arrow-annotations-tvossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvosx64/2.1.2/arrow-annotations-tvosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvosx64/2.1.2/arrow-annotations-tvosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-tvosx64/2.1.2/arrow-annotations-tvosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-tvosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../arrow-annotations-wasm-js/2.1.2/arrow-annotations-wasm-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-wasm-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../arrow-annotations-wasm-js/2.1.2/arrow-annotations-wasm-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-wasm-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../arrow-annotations-wasm-js/2.1.2/arrow-annotations-wasm-js-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-wasm-js",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosarm32/2.1.2/arrow-annotations-watchosarm32-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosarm32",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosarm32/2.1.2/arrow-annotations-watchosarm32-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosarm32",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosarm32/2.1.2/arrow-annotations-watchosarm32-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosarm32",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosarm64/2.1.2/arrow-annotations-watchosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosarm64/2.1.2/arrow-annotations-watchosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosarm64/2.1.2/arrow-annotations-watchosarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchossimulatorarm64/2.1.2/arrow-annotations-watchossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchossimulatorarm64/2.1.2/arrow-annotations-watchossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchossimulatorarm64/2.1.2/arrow-annotations-watchossimulatorarm64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchossimulatorarm64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosx64/2.1.2/arrow-annotations-watchosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosx64/2.1.2/arrow-annotations-watchosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosx64",
        "version": "2.1.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../arrow-annotations-watchosx64/2.1.2/arrow-annotations-watchosx64-2.1.2.module",
        "group": "io.arrow-kt",
        "module": "arrow-annotations-watchosx64",
        "version": "2.1.2"
      }
    }
  ]
}
