{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ajalt.mordant",
    "module": "mordant",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt.mordant",
          "module": "mordant-core",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mordant-omnibus-metadata.jar",
          "url": "mordant-3.0.2.jar",
          "size": 2477,
          "sha512": "43ebdce9d146ea15a41a6454324fa5499511effb3e53289413f065f568b112e3f87e738ff0ce1a4e51e33ded960f2e74f3eefb5f6b6a1a2f94558a27e231d6ad",
          "sha256": "090984d202692ffef447e88dfe2c63693a5de29670da0831b863bc284da147e2",
          "sha1": "241bbdbb6799cec5ae2b762ec6c2ac2b4e52cdd5",
          "md5": "8cb826265ff96b19d92e64986dd9c471"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mordant-omnibus-kotlin-sources.jar",
          "url": "mordant-3.0.2-sources.jar",
          "size": 1372,
          "sha512": "06c3d95149791468489a6d75ef684a1889718d18f0c3b85014920702140056cb131c71e18d1f9f43207ed888413dff6b281b98f78887c0fe7af2b2a024892a3b",
          "sha256": "3aa71b91497d7a6e10947949ee91039186c181fda3cc5418e49ccd5cbee98b62",
          "sha1": "f9b58b61c156089e3cf873f7de31b853a5c45b82",
          "md5": "2fbae953784e4157391e853341684d64"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iosarm64/3.0.2/mordant-iosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iosarm64/3.0.2/mordant-iosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iosarm64/3.0.2/mordant-iosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iossimulatorarm64/3.0.2/mordant-iossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iossimulatorarm64/3.0.2/mordant-iossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iossimulatorarm64/3.0.2/mordant-iossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iosx64/3.0.2/mordant-iosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iosx64/3.0.2/mordant-iosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-iosx64/3.0.2/mordant-iosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-iosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mordant-js/3.0.2/mordant-js-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mordant-js/3.0.2/mordant-js-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mordant-js/3.0.2/mordant-js-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mordant-jvm/3.0.2/mordant-jvm-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mordant-jvm/3.0.2/mordant-jvm-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../mordant-jvm/3.0.2/mordant-jvm-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-jvm",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-linuxarm64/3.0.2/mordant-linuxarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-linuxarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-linuxarm64/3.0.2/mordant-linuxarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-linuxarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-linuxx64/3.0.2/mordant-linuxx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-linuxx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-linuxx64/3.0.2/mordant-linuxx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-linuxx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-macosarm64/3.0.2/mordant-macosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-macosarm64/3.0.2/mordant-macosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-macosarm64/3.0.2/mordant-macosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-macosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-macosx64/3.0.2/mordant-macosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-macosx64/3.0.2/mordant-macosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-macosx64/3.0.2/mordant-macosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-macosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-mingwx64/3.0.2/mordant-mingwx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-mingwx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-mingwx64/3.0.2/mordant-mingwx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-mingwx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvosarm64/3.0.2/mordant-tvosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvosarm64/3.0.2/mordant-tvosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvosarm64/3.0.2/mordant-tvosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvossimulatorarm64/3.0.2/mordant-tvossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvossimulatorarm64/3.0.2/mordant-tvossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvossimulatorarm64/3.0.2/mordant-tvossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvosx64/3.0.2/mordant-tvosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvosx64/3.0.2/mordant-tvosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-tvosx64/3.0.2/mordant-tvosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-tvosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../mordant-wasm-js/3.0.2/mordant-wasm-js-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../mordant-wasm-js/3.0.2/mordant-wasm-js-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../mordant-wasm-js/3.0.2/mordant-wasm-js-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-wasm-js",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosarm32/3.0.2/mordant-watchosarm32-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosarm32/3.0.2/mordant-watchosarm32-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosarm32/3.0.2/mordant-watchosarm32-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosarm32",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosarm64/3.0.2/mordant-watchosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosarm64/3.0.2/mordant-watchosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosarm64/3.0.2/mordant-watchosarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchossimulatorarm64/3.0.2/mordant-watchossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchossimulatorarm64/3.0.2/mordant-watchossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchossimulatorarm64/3.0.2/mordant-watchossimulatorarm64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchossimulatorarm64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosx64/3.0.2/mordant-watchosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosx64/3.0.2/mordant-watchosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosx64",
        "version": "3.0.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mordant-watchosx64/3.0.2/mordant-watchosx64-3.0.2.module",
        "group": "com.github.ajalt.mordant",
        "module": "mordant-watchosx64",
        "version": "3.0.2"
      }
    }
  ]
}
