{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotest-assertions-core/6.0.3/kotest-assertions-core-6.0.3.module",
    "group": "io.kotest",
    "module": "kotest-assertions-core",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-jvm-6.0.3.jar",
          "url": "kotest-assertions-core-jvm-6.0.3.jar",
          "size": 1629395,
          "sha512": "420cd712ece5eebf416ebf88dea1841190e8732875ed10fcfd5ba94d68ec6d64a5d38dc808304c66b25b20bb18eeceb61e881f23ea64dee57167375a42fe90d9",
          "sha256": "5208111dd34ba183c1f6fc9e9cd17dd9f829349040c629d32ce2b96091714b85",
          "sha1": "1a858b559fa279a232b839f89c442b1a4e394dbc",
          "md5": "2547abde56d1884532dfc091c80c2a0a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.kotest",
          "module": "kotest-assertions-shared",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.java-diff-utils",
          "module": "java-diff-utils",
          "version": {
            "requires": "4.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-common",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotest-assertions-core-jvm-6.0.3.jar",
          "url": "kotest-assertions-core-jvm-6.0.3.jar",
          "size": 1629395,
          "sha512": "420cd712ece5eebf416ebf88dea1841190e8732875ed10fcfd5ba94d68ec6d64a5d38dc808304c66b25b20bb18eeceb61e881f23ea64dee57167375a42fe90d9",
          "sha256": "5208111dd34ba183c1f6fc9e9cd17dd9f829349040c629d32ce2b96091714b85",
          "sha1": "1a858b559fa279a232b839f89c442b1a4e394dbc",
          "md5": "2547abde56d1884532dfc091c80c2a0a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotest-assertions-core-jvm-6.0.3-sources.jar",
          "url": "kotest-assertions-core-jvm-6.0.3-sources.jar",
          "size": 226158,
          "sha512": "14972606a333c1027deb07ea56009b2637fc68d067749c0f3100fc1f564831b37ebc599d8ee871bc86a3ea77620c92a3e3036e1e432c5ef8897aa83c65e34517",
          "sha256": "7727ce0bf6715538c3564404df627696ad810260d2346346f3c91272c4c78a2f",
          "sha1": "524ac8bdd727c16e29973c9b0ad30a9cda46c3ea",
          "md5": "b65b9b433f9a12e5c49562c9b32fbadc"
        }
      ]
    }
  ]
}
