name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      version:
        description: 'Version to build (for releases)'
        required: false
        type: string
      binary-prefix:
        description: 'Binary name prefix (for releases)'
        required: false
        type: string
        default: 'scopes-build'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: read

jobs:
  cross-platform-build:
    name: Cross-Platform Native Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental == true }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: windows-latest
            platform: win32
            arch: x64
            experimental: true

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Windows Build Environment
      if: matrix.platform == 'win32'
      uses: ./.github/actions/setup-windows-build
      with:
        version: ${{ inputs.version }}

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@7f488cf82a3629ee755e4e97342c01d6bed318fa # v1.3.5
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      with:
        validate-wrappers: true
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        # Temporarily disable dependency graph due to verification metadata issues
        # dependency-graph: generate-and-submit
        # dependency-graph-continue-on-failure: true

    # Temporarily disable native compilation due to GraalVM plugin verification issues
    - name: Build JVM Application (Windows)
      if: matrix.platform == 'win32'
      run: |
        Set-Location "C:\build-workspace\scopes"
        $VERSION_ARG = ""
        if ("${{ inputs.version }}" -and "${{ inputs.version }}" -ne "") {
          $VERSION_ARG = "-Pversion=${{ inputs.version }}"
          echo "Using version argument: $VERSION_ARG"
        }
        echo "Executing: .\gradlew.bat --no-daemon build $VERSION_ARG"
        & .\gradlew.bat --no-daemon build $VERSION_ARG
      shell: powershell
      env:
        GRADLE_USER_HOME: C:\gradle-cache
        # Disable dependency graph on Windows to avoid path issues
        GITHUB_DEPENDENCY_GRAPH_ENABLED: false

    - name: Build JVM Application (Unix)
      if: matrix.platform != 'win32'
      run: |
        VERSION_ARG=""
        if [ -n "${{ inputs.version }}" ]; then
          VERSION_ARG="-Pversion=${{ inputs.version }}"
        fi
        ./gradlew --no-daemon build $VERSION_ARG

    - name: Prepare JAR for security check
      shell: bash
      run: |
        # Use a default prefix if none is provided
        PREFIX="${{ inputs.binary-prefix }}"
        if [ -z "$PREFIX" ]; then
          PREFIX="scopes-build"
        fi

        JAR_NAME="${PREFIX}-${{ matrix.platform }}-${{ matrix.arch }}.jar"
        if [ "${{ matrix.platform }}" = "win32" ]; then
          cp /c/build-workspace/scopes/presentation-cli/build/libs/presentation-cli*.jar "$JAR_NAME"
        else
          cp presentation-cli/build/libs/presentation-cli*.jar "$JAR_NAME"
        fi
        echo "binary_name=$JAR_NAME" >> $GITHUB_OUTPUT
      id: binary

    - name: Generate binary hash
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # On Windows, certutil outputs in a specific format, we need to extract just the hash
          HASH_OUTPUT=$(certutil -hashfile "${{ steps.binary.outputs.binary_name }}" SHA256)
          # Extract the second line which contains the hash
          HASH=$(echo "$HASH_OUTPUT" | sed -n '2p' | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          HASH=$(shasum -a 256 "${{ steps.binary.outputs.binary_name }}" | awk '{print $1}')
        else
          HASH=$(sha256sum "${{ steps.binary.outputs.binary_name }}" | awk '{print $1}')
        fi

        echo "Hash: $HASH"
        echo "${{ steps.binary.outputs.binary_name }}:$HASH" > binary-hash-${{ matrix.platform }}-${{ matrix.arch }}.txt

        # Set hash output for release workflow compatibility
        echo "hash=$HASH" >> $GITHUB_OUTPUT
      id: hash

    - name: Basic security checks
      shell: bash
      run: |
        echo "=== Binary Security Analysis ==="
        echo "File: ${{ steps.binary.outputs.binary_name }}"

        # File size check (reasonable size limits)
        SIZE=$(ls -la "${{ steps.binary.outputs.binary_name }}" | awk '{print $5}')
        echo "Size: $SIZE bytes"

        # Basic file type verification
        if command -v file >/dev/null 2>&1; then
          echo "File type:"
          file "${{ steps.binary.outputs.binary_name }}"
        fi

        # Check if binary is executable
        if [ "${{ matrix.platform }}" != "win32" ]; then
          if [ -x "${{ steps.binary.outputs.binary_name }}" ]; then
            echo "✅ Binary is executable"
          else
            echo "❌ Binary is not executable"
            exit 1
          fi
        fi

        # Check for suspicious strings (basic malware detection)
        if command -v strings >/dev/null 2>&1; then
          echo "Checking for suspicious strings..."
          SUSPICIOUS=$(strings "${{ steps.binary.outputs.binary_name }}" | grep -i -E "(eval|exec|system|shell|cmd|powershell|wget|curl)" | head -5 || true)
          if [ -n "$SUSPICIOUS" ]; then
            echo "⚠️ Found potentially suspicious strings (may be normal for CLI tools):"
            echo "$SUSPICIOUS"
          else
            echo "✅ No obviously suspicious strings found"
          fi
        fi

    - name: Upload binary artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: build-binary-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          ${{ steps.binary.outputs.binary_name }}
          binary-hash-${{ matrix.platform }}-${{ matrix.arch }}.txt

  binary-security-scan:
    name: Binary Security Scan
    runs-on: ubuntu-latest
    needs: cross-platform-build
    if: always() && needs.cross-platform-build.result == 'success'

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Download all binary artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        pattern: build-binary-*
        path: binaries
        merge-multiple: true

    - name: Install Grype
      uses: anchore/scan-action/download-grype@1638637db639e0ade3258b51db49a9a137574c3e # v6.5.1
      id: grype

    - name: Install Syft
      uses: anchore/sbom-action/download-syft@7b36ad622f042cab6f59a75c2ac24ccb256e9b45 # v0.20.4
      id: syft

    - name: Scan binaries with Grype
      run: |
        echo "=== Grype Vulnerability Scan ==="
        # Use the same default prefix as in the build job
        PREFIX="${{ inputs.binary-prefix }}"
        if [ -z "$PREFIX" ]; then
          PREFIX="scopes-build"
        fi

        for binary in binaries/"${PREFIX}"-*; do
          if [ -f "$binary" ] && [[ ! "$binary" == *.txt ]]; then
            echo "Scanning: $binary"
            "${{ steps.grype.outputs.cmd }}" "$binary" --output json --file "${binary}-grype-report.json" || true
            "${{ steps.grype.outputs.cmd }}" "$binary" --output table || true
            echo "---"
          fi
        done

    - name: Generate SBOMs for binaries
      run: |
        echo "=== Syft SBOM Generation ==="
        # Use the same default prefix as in the build job
        PREFIX="${{ inputs.binary-prefix }}"
        if [ -z "$PREFIX" ]; then
          PREFIX="scopes-build"
        fi

        for binary in binaries/"${PREFIX}"-*; do
          if [ -f "$binary" ] && [[ ! "$binary" == *.txt ]]; then
            echo "Generating SBOM for: $binary"
            "${{ steps.syft.outputs.cmd }}" "$binary" --output cyclonedx-json --file "${binary}-sbom.json" || true
            "${{ steps.syft.outputs.cmd }}" "$binary" --output table || true
            echo "---"
          fi
        done

    - name: Verify binary integrity
      run: |
        echo "=== Binary Integrity Verification ==="
        cd binaries
        for hash_file in binary-hash-*.txt; do
          if [ -f "$hash_file" ]; then
            echo "Verifying: $hash_file"
            cat "$hash_file"

            # Extract binary name and expected hash
            BINARY_NAME=$(cut -d':' -f1 "$hash_file")
            EXPECTED_HASH=$(cut -d':' -f2 "$hash_file")

            if [ -f "$BINARY_NAME" ]; then
              ACTUAL_HASH=$(sha256sum "$BINARY_NAME" | awk '{print $1}')
              if [ "$ACTUAL_HASH" = "$EXPECTED_HASH" ]; then
                echo "✅ $BINARY_NAME integrity verified"
              else
                echo "❌ $BINARY_NAME integrity check failed!"
                echo "Expected: $EXPECTED_HASH"
                echo "Actual: $ACTUAL_HASH"
                exit 1
              fi
            else
              echo "⚠️ Binary file $BINARY_NAME not found"
            fi
            echo "---"
          fi
        done

    - name: Upload security scan results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: security-scan-results
        path: |
          binaries/*-grype-report.json
          binaries/*-sbom.json


