name: CI

on:
  push:
    branches: [ main, setup-development-environment ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run Markdown lint
      uses: docker://davidanson/markdownlint-cli2:latest
      with:
        args: --config .markdownlint.json "**/*.md"

    - name: Run EditorConfig check
      uses: docker://mstruebing/editorconfig-checker:latest
      with:
        args: ec .

    - name: Run Kotlin lint
      run: ./gradlew ktlintCheck

    - name: Run tests
      run: ./gradlew test

    - name: Test Native Image build
      run: ./gradlew nativeCompile
