name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@7f488cf82a3629ee755e4e97342c01d6bed318fa # v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@42ebad84b0585498c0413b0967cf4e80ec0e1d19 # v4

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Run Kotlin lint
      run: ./gradlew ktlintCheck

    - name: Run Detekt static analysis
      run: ./gradlew detekt

    - name: Run tests
      run: ./gradlew test

    - name: Test Native Image build
      run: ./gradlew nativeCompile
