name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

jobs:
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/code-quality.yml
    permissions:
      contents: read

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read

  security:
    name: Security
    uses: ./.github/workflows/security-check.yml
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit

  # Summary job to require all checks to pass
  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [code-quality, test, build, security]
    if: always()

    steps:
    - name: Check all jobs status
      run: |
        if [ "${{ needs.code-quality.result }}" != "success" ] || \
           [ "${{ needs.test.result }}" != "success" ] || \
           [ "${{ needs.build.result }}" != "success" ] || \
           [ "${{ needs.security.result }}" != "success" ]; then
          echo "One or more CI checks failed"
          exit 1
        fi
        echo "All CI checks passed successfully!"
