name: CI

on:
  push:
    branches: [ main, setup-development-environment ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Markdown lint
      uses: docker://davidanson/markdownlint-cli2:latest
      with:
        args: --config .markdownlint.json "**/*.md"

    - name: Run EditorConfig check
      uses: docker://mstruebing/editorconfig-checker:latest
      with:
        args: ec .
