name: Dependency Review

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        # Fetch full git history for proper dependency diffing
        # Required for dependency-review-action to correctly compare base and head commits
        fetch-depth: 0

    - name: Dependency Review
      uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
      with:
        # Fail the build if vulnerabilities with CVSS >= 7.0 are found
        fail-on-severity: high
        # Allow security fixes to proceed
        allow-licenses: Apache-2.0, MIT, BSD-2-Clause, BSD-3-Clause, ISC, UPL-1.0
        # Comment on PR with review summary
        comment-summary-in-pr: true
        # Show only newly introduced vulnerabilities
        base-ref: ${{ github.event.pull_request.base.sha }}
        head-ref: ${{ github.event.pull_request.head.sha }}
