name: Dependency Review

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Dependency Review
      uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a # v4.4.0
      with:
        # Fail the build if vulnerabilities with CVSS >= 7.0 are found
        fail-on-severity: high
        # Allow security fixes to proceed
        allow-licenses: Apache-2.0, MIT, BSD-2-Clause, BSD-3-Clause, ISC
        # Comment on PR with review summary
        comment-summary-in-pr: true
        # Show only newly introduced vulnerabilities
        base-ref: ${{ github.event.pull_request.base.sha }}
        head-ref: ${{ github.event.pull_request.head.sha }}