name: Security Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest

    steps:
    - name: Skip duplicate actions
      uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
      with:
        concurrent_skipping: 'same_content_newer'
        skip_after_successful_duplicate: 'true'
        do_not_skip: '["workflow_dispatch", "schedule"]'

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@7f488cf82a3629ee755e4e97342c01d6bed318fa # v1.3.5
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

    - name: Submit dependency graph to GitHub
      uses: gradle/actions/dependency-submission@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
      with:
        dependency-graph: generate-and-submit

    - name: Generate SBOM (CycloneDX)
      run: ./gradlew presentation-cli:cycloneDxBom
      continue-on-error: true


    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: sbom-cyclonedx
        path: |
          presentation-cli/build/reports/bom.json
          presentation-cli/build/reports/bom.xml


    - name: Comment PR with vulnerability summary
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const comment = `## ⚠️ Security Issues Detected

          The security check found issues during SBOM generation or dependency analysis.

          Please review the [security check workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

          **Next steps:**
          1. Check the Security tab for Dependabot alerts
          2. Review any failed SBOM generation steps
          3. Update vulnerable dependencies as needed

          For more information, see [Security Policy](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.head_ref || github.ref_name }}/SECURITY.md).`;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
