name: Suppression File Review

on:
  pull_request:
    paths:
      - 'etc/owasp-suppression.xml'

permissions:
  contents: read
  pull-requests: write

jobs:
  review-suppressions:
    name: Review OWASP Suppressions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Checkout base branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.base_ref }}
        path: base

    - name: Analyze suppression changes
      id: analyze
      run: |
        # Simple diff-based analysis without XML parsing
        if [ -f "base/etc/owasp-suppression.xml" ]; then
          # Count suppressions in each file
          NEW_COUNT=$(grep -c "<suppress>" etc/owasp-suppression.xml || echo "0")
          BASE_COUNT=$(grep -c "<suppress>" base/etc/owasp-suppression.xml || echo "0")
          DIFF_COUNT=$((NEW_COUNT - BASE_COUNT))
        else
          # New file, all suppressions are new
          NEW_COUNT=$(grep -c "<suppress>" etc/owasp-suppression.xml || echo "0")
          DIFF_COUNT=$NEW_COUNT
        fi
        
        echo "new_count=$DIFF_COUNT" >> $GITHUB_OUTPUT
        echo "total_count=$NEW_COUNT" >> $GITHUB_OUTPUT

    - name: Comment on PR
      if: steps.analyze.outputs.new_count > 0
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const newCount = '${{ steps.analyze.outputs.new_count }}';
          const totalCount = '${{ steps.analyze.outputs.total_count }}';

          let comment = `## 🔍 OWASP Suppression Review Required\n\n`;
          comment += `This PR modifies suppressions in the OWASP dependency check.\n\n`;
          comment += `- **New/Modified suppressions**: ${newCount}\n`;
          comment += `- **Total suppressions**: ${totalCount}\n\n`;
          comment += `### Review Checklist\n`;
          comment += `- [ ] Each suppression has a clear \`notes\` field explaining why it's needed\n`;
          comment += `- [ ] Suppressions are truly false positives or don't affect our usage\n`;
          comment += `- [ ] No suppressions are hiding actual security risks\n`;
          comment += `- [ ] Temporary suppressions have an \`until\` date set\n\n`;
          comment += `Please review the changes in \`etc/owasp-suppression.xml\` carefully.\n\n`;
          comment += `⚠️ **Security team review is required before merging.**`;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

          // Add label
          await github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['security-review-required']
          });
