name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  pull-requests: read  # Needed for SonarCloud PR analysis

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@e140024fdc2d95d3c7e10a636887a91090d29990 # v1.4.0
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      with:
        validate-wrappers: true
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Run tests with JaCoCo coverage
      run: ./gradlew --no-daemon --scan test jacocoTestReport

    - name: Generate aggregated coverage report
      run: ./gradlew --no-daemon :quality-coverage-report:testCodeCoverageReport

    - name: Verify coverage report exists
      run: |
        if [ -f "quality/coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml" ]; then
          echo "✅ Coverage report found"
          echo "File size: $(ls -lh quality/coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml | awk '{print $5}')"
        else
          echo "❌ Coverage report not found!"
          echo "Listing available reports:"
          find . -name "*.xml" -path "*/jacoco/*" -type f
          exit 1
        fi

    - name: Run Detekt static analysis
      run: ./gradlew --no-daemon detekt

    - name: SonarCloud Scan
      continue-on-error: true  # Don't fail the workflow if SonarCloud has issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        if [ -n "$SONAR_TOKEN" ]; then
          echo "Running SonarCloud analysis..."
          ./gradlew --no-daemon sonarqube --info
        else
          echo "::notice::SonarCloud analysis skipped. To enable it, set the SONAR_TOKEN secret in repository settings."
          echo "Get your token from: https://sonarcloud.io/account/security"
        fi

    - name: Upload coverage reports
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: coverage-reports
        path: |
          **/build/reports/jacoco/
          quality/coverage-report/build/reports/jacoco/
        if-no-files-found: warn

    - name: Upload test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: test-results
        path: |
          **/build/test-results/
          **/build/reports/tests/
        if-no-files-found: warn
